### PR TITLE
Selenium: quick fix for selenium tests

### LINKED ISSUE #10784: The "Rename method" form does not close during timeout
### Remarks
**Randomly reproducing**
**Related test:** RenameVirtualMethodsTest

### Reproduction Steps
 - create and run workspace which based on default "**Java**" stack with "**web-java-spring**" project
 - create a new class **A** with next content:

``` java
class A<E>{
    public boolean add(E e) {
        return true;
    }
}

class Sub<E extends Number> extends A<E> {
    public boolean add(E e) {
        if (e.doubleValue() > 0)
            return false;
        return super.add(e);
    }
}

class Unrelated<E> {
    public boolean add(E e) {
        return false;
    }
}
```

 - select **add(E e)** method in **A** class and press **SHIFT+**F6**** twice to start "**Rename method**" form
- change the method name and click on "**OK**" button
 
**Expected behavior:**
The form is closed and the method name changed.

**Observed behavior:**
The "**Rename method**" form is not closed.

**Screencast:**
screencast-che-eclipse-che 172 19 20 234 nip io-2018 10 22-14-51-43

**Screenshots:**
selection_143

**Browser console:**
selection_144

**WS agent logs from failed RenameVirtualMethodsTest test on CI:**

**Eclipse Che network logs:** https://ci.codenvycorp.com/view/qa-nightly/job/che-integration-tests-multiuser-master-ocp/397/Selenium_20tests_20report/webdriver-logs/org.eclipse.che.selenium.refactor.methods.RenameVirtualMethodsTest.testGeneric2_time-1539813155059-millis.log

<details>

<summary>catalina-log:</summary>

```
2018-10-21 21:23:35,226[ost-startStop-1]  [INFO ] [i.WorkspaceProjectSynchronizer 66]   - Workspace ID: workspacetrsmg6oo1h267e3k
2018-10-21 21:23:35,231[ost-startStop-1]  [INFO ] [i.WorkspaceProjectSynchronizer 67]   - API Endpoint: http://che-eclipse-che.172.29.4.60.nip.io/api
2018-10-21 21:23:35,840[rcherInitThread]  [INFO ] [o.e.c.a.s.s.i.LuceneSearcher 159]    - Initial indexing complete after 5 msec 
2018-10-21 21:23:35,844[ost-startStop-1]  [INFO ] [j.i.ServerSideRequestProcessor 45]   -  che.core.jsonrpc.processor_max_pool_siz 100  
2018-10-21 21:23:47,032[ool-11-thread-1]  [INFO ] [j.l.JavaLanguageServerLauncher 98]   - Starting: Init...
2018-10-21 21:23:47,038[ool-11-thread-1]  [INFO ] [j.l.JavaLanguageServerLauncher 98]   - Starting: 0% Starting Java Language Server 
2018-10-21 21:23:47,152[rverInitializer]  [INFO ] [.a.l.LanguageServerInitializer 222]  - Initialized language server 'org.eclipse.che.plugin.java.languageserver'
2018-10-21 21:23:47,242[ool-11-thread-1]  [INFO ] [j.l.JavaLanguageServerLauncher 98]   - Starting: 30% Starting Java Language Server 
2018-10-21 21:23:48,485[ool-11-thread-1]  [INFO ] [j.l.JavaLanguageServerLauncher 98]   - Starting: 37% Starting Java Language Server 
2018-10-21 21:23:48,752[ool-11-thread-1]  [INFO ] [j.l.JavaLanguageServerLauncher 98]   - Starting: 57% Starting Java Language Server - Importing Maven project(s)
2018-10-21 21:23:48,968[ool-11-thread-1]  [INFO ] [j.l.JavaLanguageServerLauncher 98]   - Starting: 57% Starting Java Language Server - Importing Maven project(s)
2018-10-21 21:23:49,209[ool-11-thread-1]  [INFO ] [j.l.JavaLanguageServerLauncher 98]   - Starting: 57% Starting Java Language Server - Importing Maven project(s)
2018-10-21 21:23:49,411[ool-11-thread-1]  [INFO ] [j.l.JavaLanguageServerLauncher 98]   - Starting: 57% Starting Java Language Server - Importing Maven project(s)
2018-10-21 21:23:49,613[ool-11-thread-1]  [INFO ] [j.l.JavaLanguageServerLauncher 98]   - Starting: 57% Starting Java Language Server - Importing Maven project(s)
2018-10-21 21:23:49,816[ool-11-thread-1]  [INFO ] [j.l.JavaLanguageServerLauncher 98]   - Starting: 57% Starting Java Language Server - Importing Maven project(s)
2018-10-21 21:23:50,018[ool-11-thread-1]  [INFO ] [j.l.JavaLanguageServerLauncher 98]   - Starting: 57% Starting Java Language Server - Importing Maven project(s)
2018-10-21 21:23:50,222[ool-11-thread-1]  [INFO ] [j.l.JavaLanguageServerLauncher 98]   - Starting: 57% Starting Java Language Server - Importing Maven project(s)
2018-10-21 21:23:50,427[ool-11-thread-1]  [INFO ] [j.l.JavaLanguageServerLauncher 98]   - Starting: 57% Starting Java Language Server - Importing Maven project(s)
2018-10-21 21:23:50,631[ool-11-thread-1]  [INFO ] [j.l.JavaLanguageServerLauncher 98]   - Starting: 57% Starting Java Language Server - Importing Maven project(s)
2018-10-21 21:23:50,831[ool-11-thread-1]  [INFO ] [j.l.JavaLanguageServerLauncher 98]   - Starting: 57% Starting Java Language Server - Importing Maven project(s)
2018-10-21 21:23:51,037[ool-11-thread-1]  [INFO ] [j.l.JavaLanguageServerLauncher 98]   - Starting: 57% Starting Java Language Server - Importing Maven project(s)
2018-10-21 21:23:51,250[ool-11-thread-1]  [INFO ] [j.l.JavaLanguageServerLauncher 98]   - Starting: 57% Starting Java Language Server - Importing Maven project(s)
2018-10-21 21:23:51,463[ool-11-thread-1]  [INFO ] [j.l.JavaLanguageServerLauncher 98]   - Starting: 57% Starting Java Language Server - Importing Maven project(s)
2018-10-21 21:23:51,666[ool-11-thread-1]  [INFO ] [j.l.JavaLanguageServerLauncher 98]   - Starting: 57% Starting Java Language Server - Importing Maven project(s)
2018-10-21 21:23:51,868[ool-11-thread-1]  [INFO ] [j.l.JavaLanguageServerLauncher 98]   - Starting: 57% Starting Java Language Server - Importing Maven project(s)
2018-10-21 21:23:52,069[ool-11-thread-1]  [INFO ] [j.l.JavaLanguageServerLauncher 98]   - Starting: 57% Starting Java Language Server - Importing Maven project(s)
2018-10-21 21:23:52,268[ool-11-thread-1]  [INFO ] [j.l.JavaLanguageServerLauncher 98]   - Starting: 57% Starting Java Language Server - Importing Maven project(s)
2018-10-21 21:23:52,473[ool-11-thread-1]  [INFO ] [j.l.JavaLanguageServerLauncher 98]   - Starting: 57% Starting Java Language Server - Importing Maven project(s)
2018-10-21 21:23:53,385[ool-11-thread-1]  [INFO ] [j.l.JavaLanguageServerLauncher 98]   - Starting: 79% Starting Java Language Server - Importing Maven project(s)
2018-10-21 21:23:53,600[ool-11-thread-1]  [INFO ] [j.l.JavaLanguageServerLauncher 98]   - Starting: 80% Starting Java Language Server 
2018-10-21 21:23:53,803[ool-11-thread-1]  [INFO ] [j.l.JavaLanguageServerLauncher 98]   - Starting: 88% Starting Java Language Server - Configuring java project web-spring-java-simple
2018-10-21 21:23:54,004[ool-11-thread-1]  [INFO ] [j.l.JavaLanguageServerLauncher 98]   - Starting: 88% Starting Java Language Server - Configuring java project web-spring-java-simple
2018-10-21 21:23:54,205[ool-11-thread-1]  [INFO ] [j.l.JavaLanguageServerLauncher 98]   - Starting: 88% Starting Java Language Server - Configuring java project web-spring-java-simple
2018-10-21 21:23:55,001[ool-11-thread-1]  [INFO ] [j.l.JavaLanguageServerLauncher 98]   - Starting: 88% Starting Java Language Server - Configuring java project web-spring-java-simple
2018-10-21 21:23:55,179[ool-11-thread-1]  [INFO ] [j.l.JavaLanguageServerLauncher 98]   - Starting: 100% Starting Java Language Server - Resolve plugin dependency
2018-10-21 21:23:55,180[ool-11-thread-1]  [INFO ] [j.l.JavaLanguageServerLauncher 98]   - Starting: 100% Starting Java Language Server - Resolve plugin dependency
2018-10-21 21:23:55,192[ool-11-thread-1]  [INFO ] [j.l.JavaLanguageServerLauncher 98]   - Started: Ready
2018-10-21 21:23:55,300[ool-11-thread-1]  [INFO ] [j.l.JavaLanguageServerLauncher 98]   - Starting: 100% Starting Java Language Server - Resolve plugin dependency
2018-10-21 21:23:55,397[ool-11-thread-1]  [INFO ] [j.l.JavaLanguageServerLauncher 98]   - Message: Updating workspace folders: Adding 1 folder(s), removing 0 folders.
2018-10-21 21:23:55,486[kspaceUpdater-0]  [INFO ] [.c.p.j.l.WorkspaceSynchronizer 80]   - Workspace updated. Result code: '0', message: 'OK'. Added projects: '[file:///projects/RenameVirtualMethodsTest4016]', removed projects: '[]'
```
</details>

<details>

<summary>Browser console logs:</summary>

```
Browser console logs:
---------------------
2018-10-17 09:45:52,346 WARNING http://keycloak-eclipse-che.172.29.4.88.nip.io/auth/realms/che/protocol/openid-connect/auth?client_id=che-public&redirect_uri=http%3A%2F%2Fche-eclipse-che.172.29.4.88.nip.io%2Fuser1539805808090%2Fworkspaces9552i&state=4a3e46ad-efff-4a39-87d2-f82d29ffce16&nonce=640f433c-6f70-4512-9599-fef2479cc88b&response_mode=fragment&response_type=code&scope=openid - This page includes a password or credit card input in a non-secure context. A warning has been added to the URL bar. For more information, see https://goo.gl/zmWq3m.

2018-10-17 09:45:56,543 INFO http://keycloak-eclipse-che.172.29.4.88.nip.io/auth/js/keycloak.js 684:28 "[KEYCLOAK] Estimated time difference between browser and server is 0 seconds"

2018-10-17 09:51:09,188 INFO http://keycloak-eclipse-che.172.29.4.88.nip.io/auth/js/keycloak.js 409:28 "[KEYCLOAK] Refreshing token: token expired"

2018-10-17 09:51:09,189 INFO http://keycloak-eclipse-che.172.29.4.88.nip.io/auth/js/keycloak.js 437:44 "[KEYCLOAK] Token refreshed"

2018-10-17 09:51:09,189 INFO http://keycloak-eclipse-che.172.29.4.88.nip.io/auth/js/keycloak.js 684:28 "[KEYCLOAK] Estimated time difference between browser and server is 0 seconds"

2018-10-17 09:52:23,343 SEVERE _app-0.js 12974:115 Uncaught TypeError: Cannot read property 'b' of undefined

```
</details>

<details>

<summary>localhost-acess-log</summary>

```
172.17.42.1 - - [17/Oct/2018:21:45:41 +0000] "GET /api/ HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:45:44 +0000] "GET /api/ HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:45:48 +0000] "POST /api/project/import/RenameVirtualMethodsTest3526 HTTP/1.1" 201 -
172.17.42.1 - - [17/Oct/2018:21:45:49 +0000] "PUT /api/project/RenameVirtualMethodsTest3526 HTTP/1.1" 200 678
172.17.42.1 - - [17/Oct/2018:21:45:54 +0000] "GET /api/liveness HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:46:04 +0000] "GET /api/liveness HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:46:07 +0000] "OPTIONS /api/project-type HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:46:07 +0000] "GET /wsagent?token=eyJhbGciOiJSUzI1NiIsImtpbmQiOiJtYWNoaW5lX3Rva2VuIiwia2lkIjoid29ya3NwYWNlOHd1b3g4MTZ3djBoMDQ1eCJ9.eyJ3c2lkIjoid29ya3NwYWNlOHd1b3g4MTZ3djBoMDQ1eCIsInVpZCI6IjM3NjgwMWFiLTdmMWYtNDE2OS1iMzM2LTJmNTM0ZjVhY2E1MCIsImF1ZCI6IndvcmtzcGFjZTh3dW94ODE2d3YwaDA0NXgiLCJuYmYiOi0xLCJ1bmFtZSI6InVzZXIxNTM5ODA1ODA4MDkwIiwiaXNzIjoid3NtYXN0ZXIiLCJleHAiOjE1NzEzNDg3MDcsImlhdCI6MTUzOTgxMjcwNywianRpIjoiYjg2NmU0OTktYjg4NS00NTRhLThkZTYtY2Q4Y2IyYjEwMjViIn0.IBNkoo2WuURf1xfP5CWhDOSyLQxixRxzC8YvUAsvqnGqzOuEkWnn4Bd9-7fFp-qCXD1FmNXYk8uWqpIdn-P51FQZe_UFrPsN1dKTfxdqQJRCSgl0ViQvHBaQi0oOnpzgY6kQPDOMIhRU6SG__cDR2HwFNmaghqWWobQgimPIFW2yTHRlB_DG3vtzMq2m40JbAnxTi-ToXsnJqrDmxboOQ3ZRmrAq8FBI5EfsAlScr8M6RD8vgd47NxwmWf1-RplVzHFiK_uFYXTUHjCqtkt-U1I0bGTcJtOz_BvpG9zfTshT0NHnDN_q8zgJCsW0RMyNZsWoTWknrSahH8pCLoq2fw HTTP/1.1" 101 -
172.17.42.1 - - [17/Oct/2018:21:46:08 +0000] "GET /api/project-type HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:46:08 +0000] "OPTIONS /api/project HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:46:08 +0000] "GET /api/project HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:46:09 +0000] "OPTIONS /api/app/state?userId=376801ab-7f1f-4169-b336-2f534f5aca50 HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:46:09 +0000] "GET /api/app/state?userId=376801ab-7f1f-4169-b336-2f534f5aca50 HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:46:14 +0000] "GET /api/liveness HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:46:24 +0000] "GET /api/liveness HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:46:34 +0000] "GET /api/liveness HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:46:44 +0000] "GET /api/liveness HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:46:54 +0000] "GET /api/liveness HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:47:04 +0000] "GET /api/liveness HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:47:14 +0000] "GET /api/liveness HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:47:24 +0000] "GET /api/liveness HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:47:34 +0000] "GET /api/liveness HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:47:44 +0000] "GET /api/liveness HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:47:54 +0000] "GET /api/liveness HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:48:04 +0000] "GET /api/liveness HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:48:14 +0000] "GET /api/liveness HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:48:24 +0000] "GET /api/liveness HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:48:34 +0000] "GET /api/liveness HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:48:45 +0000] "GET /api/liveness HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:48:55 +0000] "GET /api/liveness HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:49:05 +0000] "GET /api/liveness HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:49:12 +0000] "OPTIONS /api/project/tree/?depth=-1&includeFiles=true HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:49:12 +0000] "GET /api/project/tree/?depth=-1&includeFiles=true HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:49:12 +0000] "OPTIONS /api/project/tree/RenameVirtualMethodsTest3526?depth=1&includeFiles=true HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:49:12 +0000] "GET /api/project/tree/RenameVirtualMethodsTest3526?depth=1&includeFiles=true HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:49:12 +0000] "OPTIONS /api/project/tree/RenameVirtualMethodsTest3526/src?depth=1&includeFiles=true HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:49:12 +0000] "OPTIONS /api/project/tree/RenameVirtualMethodsTest3526/target?depth=1&includeFiles=true HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:49:12 +0000] "GET /api/project/tree/RenameVirtualMethodsTest3526/src?depth=1&includeFiles=true HTTP/1.1" 200 1489
172.17.42.1 - - [17/Oct/2018:21:49:12 +0000] "GET /api/project/tree/RenameVirtualMethodsTest3526/target?depth=1&includeFiles=true HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:49:12 +0000] "OPTIONS /api/project/tree/RenameVirtualMethodsTest3526/src/main?depth=1&includeFiles=true HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:49:12 +0000] "OPTIONS /api/project/tree/RenameVirtualMethodsTest3526/target/classes?depth=1&includeFiles=true HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:49:12 +0000] "OPTIONS /api/project/tree/RenameVirtualMethodsTest3526/target/test-classes?depth=1&includeFiles=true HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:49:12 +0000] "GET /api/project/tree/RenameVirtualMethodsTest3526/target/classes?depth=1&includeFiles=true HTTP/1.1" 200 1661
172.17.42.1 - - [17/Oct/2018:21:49:12 +0000] "GET /api/project/tree/RenameVirtualMethodsTest3526/src/main?depth=1&includeFiles=true HTTP/1.1" 200 1530
172.17.42.1 - - [17/Oct/2018:21:49:12 +0000] "GET /api/project/tree/RenameVirtualMethodsTest3526/target/test-classes?depth=1&includeFiles=true HTTP/1.1" 200 807
172.17.42.1 - - [17/Oct/2018:21:49:12 +0000] "GET /api/project/tree/RenameVirtualMethodsTest3526/target/test-classes?depth=1&includeFiles=true HTTP/1.1" 200 807
172.17.42.1 - - [17/Oct/2018:21:49:12 +0000] "OPTIONS /api/project/tree/RenameVirtualMethodsTest3526/target/classes/renameVirtualMethods?depth=1&includeFiles=true HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:49:12 +0000] "OPTIONS /api/project/tree/RenameVirtualMethodsTest3526/src/main/java?depth=1&includeFiles=true HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:49:12 +0000] "GET /api/project/tree/RenameVirtualMethodsTest3526/src/main/java?depth=1&includeFiles=true HTTP/1.1" 200 1650
172.17.42.1 - - [17/Oct/2018:21:49:12 +0000] "GET /api/project/tree/RenameVirtualMethodsTest3526/target/classes/renameVirtualMethods?depth=1&includeFiles=true HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:49:12 +0000] "OPTIONS /api/project/tree/RenameVirtualMethodsTest3526/src/main/java/renameVirtualMethods?depth=1&includeFiles=true HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:49:13 +0000] "GET /api/project/tree/RenameVirtualMethodsTest3526/src/main/java/renameVirtualMethods?depth=1&includeFiles=true HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:49:13 +0000] "OPTIONS /api/project/tree/RenameVirtualMethodsTest3526/target/classes/renameVirtualMethods/test1?depth=1&includeFiles=true HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:49:13 +0000] "OPTIONS /api/project/tree/RenameVirtualMethodsTest3526/target/classes/renameVirtualMethods/test11?depth=1&includeFiles=true HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:49:13 +0000] "OPTIONS /api/project/tree/RenameVirtualMethodsTest3526/target/classes/renameVirtualMethods/test25?depth=1&includeFiles=true HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:49:13 +0000] "OPTIONS /api/project/tree/RenameVirtualMethodsTest3526/target/classes/renameVirtualMethods/testEnum2?depth=1&includeFiles=true HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:49:13 +0000] "OPTIONS /api/project/tree/RenameVirtualMethodsTest3526/target/classes/renameVirtualMethods/testFail35?depth=1&includeFiles=true HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:49:13 +0000] "OPTIONS /api/project/tree/RenameVirtualMethodsTest3526/target/classes/renameVirtualMethods/testVarArgs1?depth=1&includeFiles=true HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:49:13 +0000] "OPTIONS /api/project/tree/RenameVirtualMethodsTest3526/target/classes/renameVirtualMethods/testGeneric2?depth=1&includeFiles=true HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:49:13 +0000] "GET /api/project/tree/RenameVirtualMethodsTest3526/target/classes/renameVirtualMethods/test1?depth=1&includeFiles=true HTTP/1.1" 200 1806
172.17.42.1 - - [17/Oct/2018:21:49:13 +0000] "GET /api/project/tree/RenameVirtualMethodsTest3526/target/classes/renameVirtualMethods/test11?depth=1&includeFiles=true HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:49:13 +0000] "GET /api/project/tree/RenameVirtualMethodsTest3526/target/classes/renameVirtualMethods/test25?depth=1&includeFiles=true HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:49:13 +0000] "GET /api/project/tree/RenameVirtualMethodsTest3526/target/classes/renameVirtualMethods/testEnum2?depth=1&includeFiles=true HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:49:13 +0000] "GET /api/project/tree/RenameVirtualMethodsTest3526/target/classes/renameVirtualMethods/testVarArgs1?depth=1&includeFiles=true HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:49:13 +0000] "GET /api/project/tree/RenameVirtualMethodsTest3526/target/classes/renameVirtualMethods/testFail35?depth=1&includeFiles=true HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:49:13 +0000] "GET /api/project/tree/RenameVirtualMethodsTest3526/src/main/java/renameVirtualMethods?depth=1&includeFiles=true HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:49:13 +0000] "GET /api/project/tree/RenameVirtualMethodsTest3526/target/classes/renameVirtualMethods/testGeneric2?depth=1&includeFiles=true HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:49:13 +0000] "OPTIONS /api/project/tree/RenameVirtualMethodsTest3526/src/main/java/renameVirtualMethods/test1?depth=1&includeFiles=true HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:49:13 +0000] "OPTIONS /api/project/tree/RenameVirtualMethodsTest3526/src/main/java/renameVirtualMethods/test11?depth=1&includeFiles=true HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:49:13 +0000] "OPTIONS /api/project/tree/RenameVirtualMethodsTest3526/src/main/java/renameVirtualMethods/test25?depth=1&includeFiles=true HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:49:13 +0000] "OPTIONS /api/project/tree/RenameVirtualMethodsTest3526/src/main/java/renameVirtualMethods/testFail35?depth=1&includeFiles=true HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:49:13 +0000] "OPTIONS /api/project/tree/RenameVirtualMethodsTest3526/src/main/java/renameVirtualMethods/testEnum2?depth=1&includeFiles=true HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:49:13 +0000] "OPTIONS /api/project/tree/RenameVirtualMethodsTest3526/src/main/java/renameVirtualMethods/testGeneric2?depth=1&includeFiles=true HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:49:13 +0000] "OPTIONS /api/project/tree/RenameVirtualMethodsTest3526/src/main/java/renameVirtualMethods/testVarArgs1?depth=1&includeFiles=true HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:49:13 +0000] "GET /api/project/tree/RenameVirtualMethodsTest3526/src/main/java/renameVirtualMethods/test1?depth=1&includeFiles=true HTTP/1.1" 200 1793
172.17.42.1 - - [17/Oct/2018:21:49:13 +0000] "GET /api/project/tree/RenameVirtualMethodsTest3526/src/main/java/renameVirtualMethods/test11?depth=1&includeFiles=true HTTP/1.1" 200 1802
172.17.42.1 - - [17/Oct/2018:21:49:13 +0000] "GET /api/project/tree/RenameVirtualMethodsTest3526/src/main/java/renameVirtualMethods/test25?depth=1&includeFiles=true HTTP/1.1" 200 1802
172.17.42.1 - - [17/Oct/2018:21:49:13 +0000] "GET /api/project/tree/RenameVirtualMethodsTest3526/src/main/java/renameVirtualMethods/testEnum2?depth=1&includeFiles=true HTTP/1.1" 200 1829
172.17.42.1 - - [17/Oct/2018:21:49:13 +0000] "GET /api/project/tree/RenameVirtualMethodsTest3526/src/main/java/renameVirtualMethods/testFail35?depth=1&includeFiles=true HTTP/1.1" 200 1838
172.17.42.1 - - [17/Oct/2018:21:49:13 +0000] "GET /api/project/tree/RenameVirtualMethodsTest3526/src/main/java/renameVirtualMethods/testGeneric2?depth=1&includeFiles=true HTTP/1.1" 200 1856
172.17.42.1 - - [17/Oct/2018:21:49:13 +0000] "GET /api/project/tree/RenameVirtualMethodsTest3526/src/main/java/renameVirtualMethods/testVarArgs1?depth=1&includeFiles=true HTTP/1.1" 200 1857
172.17.42.1 - - [17/Oct/2018:21:49:13 +0000] "GET /api/project/tree/RenameVirtualMethodsTest3526/src/main/java/renameVirtualMethods/test1?depth=1&includeFiles=true HTTP/1.1" 200 1793
172.17.42.1 - - [17/Oct/2018:21:49:13 +0000] "GET /api/project/tree/RenameVirtualMethodsTest3526/src/main/java/renameVirtualMethods/test11?depth=1&includeFiles=true HTTP/1.1" 200 1802
172.17.42.1 - - [17/Oct/2018:21:49:13 +0000] "GET /api/project/tree/RenameVirtualMethodsTest3526/src/main/java/renameVirtualMethods/test25?depth=1&includeFiles=true HTTP/1.1" 200 1802
172.17.42.1 - - [17/Oct/2018:21:49:13 +0000] "GET /api/project/tree/RenameVirtualMethodsTest3526/src/main/java/renameVirtualMethods/testEnum2?depth=1&includeFiles=true HTTP/1.1" 200 1829
172.17.42.1 - - [17/Oct/2018:21:49:13 +0000] "GET /api/project/tree/RenameVirtualMethodsTest3526/src/main/java/renameVirtualMethods/testFail35?depth=1&includeFiles=true HTTP/1.1" 200 1838
172.17.42.1 - - [17/Oct/2018:21:49:13 +0000] "GET /api/project/tree/RenameVirtualMethodsTest3526/src/main/java/renameVirtualMethods/testVarArgs1?depth=1&includeFiles=true HTTP/1.1" 200 1857
172.17.42.1 - - [17/Oct/2018:21:49:13 +0000] "GET /api/project/tree/RenameVirtualMethodsTest3526/src/main/java/renameVirtualMethods/testGeneric2?depth=1&includeFiles=true HTTP/1.1" 200 1856
172.17.42.1 - - [17/Oct/2018:21:49:13 +0000] "GET /api/project/tree/RenameVirtualMethodsTest3526?depth=1&includeFiles=true HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:49:14 +0000] "GET /api/project/tree/RenameVirtualMethodsTest3526/src?depth=1&includeFiles=true HTTP/1.1" 200 1489
172.17.42.1 - - [17/Oct/2018:21:49:14 +0000] "GET /api/project/tree/RenameVirtualMethodsTest3526/target?depth=1&includeFiles=true HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:49:14 +0000] "GET /api/project/tree/RenameVirtualMethodsTest3526/src/main?depth=1&includeFiles=true HTTP/1.1" 200 1530
172.17.42.1 - - [17/Oct/2018:21:49:14 +0000] "GET /api/project/tree/RenameVirtualMethodsTest3526/target/classes?depth=1&includeFiles=true HTTP/1.1" 200 1661
172.17.42.1 - - [17/Oct/2018:21:49:14 +0000] "GET /api/project/tree/RenameVirtualMethodsTest3526/src/main/java?depth=1&includeFiles=true HTTP/1.1" 200 1650
172.17.42.1 - - [17/Oct/2018:21:49:14 +0000] "GET /api/project/tree/RenameVirtualMethodsTest3526/target/classes/renameVirtualMethods?depth=1&includeFiles=true HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:49:14 +0000] "GET /api/project/tree/RenameVirtualMethodsTest3526/src/main/java/renameVirtualMethods?depth=1&includeFiles=true HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:49:14 +0000] "GET /api/project/tree/RenameVirtualMethodsTest3526/target/classes/renameVirtualMethods/test1?depth=1&includeFiles=true HTTP/1.1" 200 1806
172.17.42.1 - - [17/Oct/2018:21:49:14 +0000] "GET /api/project/tree/RenameVirtualMethodsTest3526/target/classes/renameVirtualMethods/test11?depth=1&includeFiles=true HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:49:14 +0000] "GET /api/project/tree/RenameVirtualMethodsTest3526/target/classes/renameVirtualMethods/testGeneric2?depth=1&includeFiles=true HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:49:14 +0000] "GET /api/project/tree/RenameVirtualMethodsTest3526/target/classes/renameVirtualMethods/test25?depth=1&includeFiles=true HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:49:14 +0000] "GET /api/project/tree/RenameVirtualMethodsTest3526/target/classes/renameVirtualMethods/testVarArgs1?depth=1&includeFiles=true HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:49:14 +0000] "GET /api/project/tree/RenameVirtualMethodsTest3526/target/classes/renameVirtualMethods/testFail35?depth=1&includeFiles=true HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:49:14 +0000] "GET /api/project/tree/RenameVirtualMethodsTest3526/target/classes/renameVirtualMethods/testEnum2?depth=1&includeFiles=true HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:49:14 +0000] "GET /api/project/tree/RenameVirtualMethodsTest3526/src/main/java/renameVirtualMethods?depth=1&includeFiles=true HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:49:14 +0000] "GET /api/project/tree/RenameVirtualMethodsTest3526/src/main/java/renameVirtualMethods/test1?depth=1&includeFiles=true HTTP/1.1" 200 1793
172.17.42.1 - - [17/Oct/2018:21:49:14 +0000] "GET /api/project/tree/RenameVirtualMethodsTest3526/src/main/java/renameVirtualMethods/test11?depth=1&includeFiles=true HTTP/1.1" 200 1802
172.17.42.1 - - [17/Oct/2018:21:49:14 +0000] "GET /api/project/tree/RenameVirtualMethodsTest3526/src/main/java/renameVirtualMethods/testFail35?depth=1&includeFiles=true HTTP/1.1" 200 1838
172.17.42.1 - - [17/Oct/2018:21:49:14 +0000] "GET /api/project/tree/RenameVirtualMethodsTest3526/src/main/java/renameVirtualMethods/testEnum2?depth=1&includeFiles=true HTTP/1.1" 200 1829
172.17.42.1 - - [17/Oct/2018:21:49:14 +0000] "GET /api/project/tree/RenameVirtualMethodsTest3526/src/main/java/renameVirtualMethods/test25?depth=1&includeFiles=true HTTP/1.1" 200 1802
172.17.42.1 - - [17/Oct/2018:21:49:14 +0000] "GET /api/project/tree/RenameVirtualMethodsTest3526/src/main/java/renameVirtualMethods/testGeneric2?depth=1&includeFiles=true HTTP/1.1" 200 1856
172.17.42.1 - - [17/Oct/2018:21:49:14 +0000] "GET /api/project/tree/RenameVirtualMethodsTest3526/src/main/java/renameVirtualMethods/testVarArgs1?depth=1&includeFiles=true HTTP/1.1" 200 1857
172.17.42.1 - - [17/Oct/2018:21:49:14 +0000] "GET /api/project/tree/RenameVirtualMethodsTest3526/src/main/java/renameVirtualMethods/test11?depth=1&includeFiles=true HTTP/1.1" 200 1802
172.17.42.1 - - [17/Oct/2018:21:49:14 +0000] "GET /api/project/tree/RenameVirtualMethodsTest3526/src/main/java/renameVirtualMethods/test1?depth=1&includeFiles=true HTTP/1.1" 200 1793
172.17.42.1 - - [17/Oct/2018:21:49:14 +0000] "GET /api/project/tree/RenameVirtualMethodsTest3526/src/main/java/renameVirtualMethods/test25?depth=1&includeFiles=true HTTP/1.1" 200 1802
172.17.42.1 - - [17/Oct/2018:21:49:14 +0000] "GET /api/project/tree/RenameVirtualMethodsTest3526/src/main/java/renameVirtualMethods/testEnum2?depth=1&includeFiles=true HTTP/1.1" 200 1829
172.17.42.1 - - [17/Oct/2018:21:49:14 +0000] "GET /api/project/tree/RenameVirtualMethodsTest3526/src/main/java/renameVirtualMethods/testFail35?depth=1&includeFiles=true HTTP/1.1" 200 1838
172.17.42.1 - - [17/Oct/2018:21:49:14 +0000] "GET /api/project/tree/RenameVirtualMethodsTest3526/src/main/java/renameVirtualMethods/testGeneric2?depth=1&includeFiles=true HTTP/1.1" 200 1856
172.17.42.1 - - [17/Oct/2018:21:49:14 +0000] "GET /api/project/tree/RenameVirtualMethodsTest3526/src/main/java/renameVirtualMethods/testVarArgs1?depth=1&includeFiles=true HTTP/1.1" 200 1857
172.17.42.1 - - [17/Oct/2018:21:49:15 +0000] "GET /api/liveness HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:49:16 +0000] "OPTIONS /api/project/file/RenameVirtualMethodsTest3526/src/main/java/renameVirtualMethods/test1/A.java HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:49:16 +0000] "GET /api/project/file/RenameVirtualMethodsTest3526/src/main/java/renameVirtualMethods/test1/A.java HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:49:17 +0000] "GET /api/project/file/RenameVirtualMethodsTest3526/src/main/java/renameVirtualMethods/test1/A.java HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:49:25 +0000] "GET /api/liveness HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:49:32 +0000] "OPTIONS /api/project/file/RenameVirtualMethodsTest3526/src/main/java/renameVirtualMethods/test1/A.java HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:49:32 +0000] "OPTIONS /api/project/file/RenameVirtualMethodsTest3526/src/main/java/renameVirtualMethods/test1/A.java HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:49:32 +0000] "GET /api/project/file/RenameVirtualMethodsTest3526/src/main/java/renameVirtualMethods/test1/A.java HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:49:32 +0000] "PUT /api/project/file/RenameVirtualMethodsTest3526/src/main/java/renameVirtualMethods/test1/A.java HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:49:35 +0000] "GET /api/liveness HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:49:41 +0000] "OPTIONS /api/project/file/RenameVirtualMethodsTest3526/src/main/java/renameVirtualMethods/test11/A.java HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:49:41 +0000] "GET /api/project/file/RenameVirtualMethodsTest3526/src/main/java/renameVirtualMethods/test11/A.java HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:49:41 +0000] "GET /api/project/file/RenameVirtualMethodsTest3526/src/main/java/renameVirtualMethods/test11/A.java HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:49:45 +0000] "GET /api/liveness HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:49:55 +0000] "GET /api/liveness HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:49:58 +0000] "OPTIONS /api/project/file/RenameVirtualMethodsTest3526/src/main/java/renameVirtualMethods/test11/A.java HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:49:58 +0000] "GET /api/project/file/RenameVirtualMethodsTest3526/src/main/java/renameVirtualMethods/test11/A.java HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:49:58 +0000] "OPTIONS /api/project/file/RenameVirtualMethodsTest3526/src/main/java/renameVirtualMethods/test11/A.java HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:49:58 +0000] "PUT /api/project/file/RenameVirtualMethodsTest3526/src/main/java/renameVirtualMethods/test11/A.java HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:50:05 +0000] "GET /api/liveness HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:50:08 +0000] "OPTIONS /api/project/file/RenameVirtualMethodsTest3526/src/main/java/renameVirtualMethods/test25/A.java HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:50:08 +0000] "GET /api/project/file/RenameVirtualMethodsTest3526/src/main/java/renameVirtualMethods/test25/A.java HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:50:08 +0000] "GET /api/project/file/RenameVirtualMethodsTest3526/src/main/java/renameVirtualMethods/test25/A.java HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:50:15 +0000] "GET /api/liveness HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:50:25 +0000] "GET /api/liveness HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:50:32 +0000] "OPTIONS /api/project/file/RenameVirtualMethodsTest3526/src/main/java/renameVirtualMethods/test25/A.java HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:50:32 +0000] "PUT /api/project/file/RenameVirtualMethodsTest3526/src/main/java/renameVirtualMethods/test25/A.java HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:50:35 +0000] "GET /api/liveness HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:50:38 +0000] "OPTIONS /api/project/file/RenameVirtualMethodsTest3526/src/main/java/renameVirtualMethods/testEnum2/A.java HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:50:38 +0000] "GET /api/project/file/RenameVirtualMethodsTest3526/src/main/java/renameVirtualMethods/testEnum2/A.java HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:50:38 +0000] "GET /api/project/file/RenameVirtualMethodsTest3526/src/main/java/renameVirtualMethods/testEnum2/A.java HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:50:45 +0000] "GET /api/liveness HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:50:55 +0000] "GET /api/liveness HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:51:00 +0000] "OPTIONS /api/project/file/RenameVirtualMethodsTest3526/src/main/java/renameVirtualMethods/testEnum2/A.java HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:51:00 +0000] "OPTIONS /api/project/file/RenameVirtualMethodsTest3526/src/main/java/renameVirtualMethods/testEnum2/A.java HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:51:00 +0000] "GET /api/project/file/RenameVirtualMethodsTest3526/src/main/java/renameVirtualMethods/testEnum2/A.java HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:51:00 +0000] "PUT /api/project/file/RenameVirtualMethodsTest3526/src/main/java/renameVirtualMethods/testEnum2/A.java HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:51:05 +0000] "GET /api/liveness HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:51:14 +0000] "OPTIONS /api/project/file/RenameVirtualMethodsTest3526/src/main/java/renameVirtualMethods/testFail35/A.java HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:51:14 +0000] "GET /api/project/file/RenameVirtualMethodsTest3526/src/main/java/renameVirtualMethods/testFail35/A.java HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:51:14 +0000] "GET /api/project/file/RenameVirtualMethodsTest3526/src/main/java/renameVirtualMethods/testFail35/A.java HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:51:15 +0000] "GET /api/liveness HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:51:25 +0000] "GET /api/liveness HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:51:35 +0000] "GET /api/liveness HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:51:37 +0000] "OPTIONS /api/project/file/RenameVirtualMethodsTest3526/src/main/java/renameVirtualMethods/testFail35/A.java HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:51:37 +0000] "PUT /api/project/file/RenameVirtualMethodsTest3526/src/main/java/renameVirtualMethods/testFail35/A.java HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:51:45 +0000] "OPTIONS /api/project/file/RenameVirtualMethodsTest3526/src/main/java/renameVirtualMethods/testGeneric2/A.java HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:51:45 +0000] "GET /api/project/file/RenameVirtualMethodsTest3526/src/main/java/renameVirtualMethods/testGeneric2/A.java HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:51:45 +0000] "GET /api/project/file/RenameVirtualMethodsTest3526/src/main/java/renameVirtualMethods/testGeneric2/A.java HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:51:45 +0000] "GET /api/liveness HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:51:55 +0000] "GET /api/liveness HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:52:05 +0000] "GET /api/liveness HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:52:15 +0000] "GET /api/liveness HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:52:25 +0000] "GET /api/liveness HTTP/1.1" 200 -
172.17.42.1 - - [17/Oct/2018:21:52:35 +0000] "GET /api/liveness HTTP/1.1" 200 -
```
</details>
**OS and version:**    
Che 6.10.0-SNAPSHOT; Chrome 63.0; Fedora 28

### PR DESCRIPTION
**Pull request by SkorikSergey**
### What does this PR do?
This PR:
- update expected stacks list in **NewWorkspacePageTest** selenium test according to https://github.com/eclipse/che/pull/11661;
- increase timeout for checking that 'Refactor rename' form is closed(it maybe fix https://github.com/eclipse/che/issues/10784 issue);
- set **che.workspace_agent_dev_inactive_stop_timeout_ms property** to 420000 ms;
- remove **ConvertToMavenProjectTest** and **RefactoringFeatureTest** selenium tests from **CheSuite** test suite.

### CODE REVIEW

File: selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/Refactor.java [hunk 1]
```diff
@@ -82,6 +84,7 @@ public Refactor(
     this.redrawUiElementWait = new WebDriverWait(seleniumWebDriver, REDRAW_UI_ELEMENTS_TIMEOUT_SEC);
     this.loadPageWait = new WebDriverWait(seleniumWebDriver, LOAD_PAGE_TIMEOUT_SEC);
     this.elementWait = new WebDriverWait(seleniumWebDriver, ELEMENT_TIMEOUT_SEC);
+    this.widgetTimeout = new WebDriverWait(seleniumWebDriver, WIDGET_TIMEOUT_SEC);
```
Comment (dmytro-ndp) [inline selenium/che-selenium-test/src/main/java/org/eclipse/che/selenium/pageobject/Refactor.java]: Let's use _SeleniumWebDriverHelper_ instead creating _WebDriverWait_ instance directly.

**Review by dmytro-ndp — APPROVED** [review]

**Review by artaleks9 — APPROVED** [review]
