### PR TITLE
CHE-6191: FIx bug when can not open project in workspace with custom …

### LINKED ISSUE #6191: Project explorer cannot open any project if `WORKDIR` is not set to `/projects/`
For any custom stack that has a docker image with WORKDIR not set to `/projects`
Project explorer cannot access expand projects.

**Reproduction Steps:**
- Create a new workspace based on a custom docker image with `WORKDIR /home/user`
- After importing any project, the project has red cross, we can browse the project files from the terminal, we cannot browse project from explorer. Expanding a project, import project popup appears. we can see http 500 error code network errors when accessing to 

eclipse che - rh-che-249-rm-upstre - chromium_061

selection_062

### PR DESCRIPTION
**Pull request by vinokurig**
…WORKDIR property

### What does this PR do?
FIx bug when can not open project in workspace with custom WORKDIR property

### What issues does this PR fix or reference?
fixes https://github.com/eclipse/che/issues/6191

#### Changelog
FIx bug when can not open project in workspace with custom WORKDIR property

#### Release Notes

N/A

#### Docs PR

N/A

### CODE REVIEW

File: wsagent/che-core-api-git/src/main/java/org/eclipse/che/api/git/GitChangesDetector.java [hunk 1]
```diff
@@ -58,9 +61,11 @@
   public GitChangesDetector(
       RequestTransmitter transmitter,
       FileWatcherManager manager,
+      ProjectManager projectManager,
```
Comment (vparfonov) [inline wsagent/che-core-api-git/src/main/java/org/eclipse/che/api/git/GitChangesDetector.java]: Use here `Provider<ProjectManager>`

File: wsagent/che-core-api-git/src/main/java/org/eclipse/che/api/git/GitIndexChangedDetector.java [hunk 2]
```diff
@@ -55,9 +58,11 @@
   public GitIndexChangedDetector(
       RequestTransmitter transmitter,
       FileWatcherManager manager,
+      ProjectManager projectManager,
```
Comment (vparfonov) [inline wsagent/che-core-api-git/src/main/java/org/eclipse/che/api/git/GitIndexChangedDetector.java]: Use here `Provider<ProjectManager>`

File: wsagent/che-core-api-git/src/main/java/org/eclipse/che/api/git/GitStatusProvider.java [hunk 3]
```diff
@@ -24,10 +26,13 @@
  */
 public class GitStatusProvider implements VcsStatusProvider {
   private final GitConnectionFactory gitConnectionFactory;
+  private final ProjectManager projectManager;
 
   @Inject
-  public GitStatusProvider(GitConnectionFactory gitConnectionFactory) {
+  public GitStatusProvider(
+      GitConnectionFactory gitConnectionFactory, ProjectManager projectManager) {
```
Comment (vparfonov) [inline wsagent/che-core-api-git/src/main/java/org/eclipse/che/api/git/GitStatusProvider.java]: Use here `Provider<ProjectManager>`

File: wsagent/che-core-api-git/src/main/java/org/eclipse/che/api/git/GitChangesDetector.java (hunk 1 above)
Comment (vinokurig) [reply wsagent/che-core-api-git/src/main/java/org/eclipse/che/api/git/GitChangesDetector.java]: done

File: wsagent/che-core-api-git/src/main/java/org/eclipse/che/api/git/GitIndexChangedDetector.java (hunk 2 above)
Comment (vinokurig) [reply wsagent/che-core-api-git/src/main/java/org/eclipse/che/api/git/GitIndexChangedDetector.java]: done

File: wsagent/che-core-api-git/src/main/java/org/eclipse/che/api/git/GitStatusProvider.java (hunk 3 above)
Comment (vinokurig) [reply wsagent/che-core-api-git/src/main/java/org/eclipse/che/api/git/GitStatusProvider.java]: done

**Review by vparfonov — APPROVED** [review]

**Comment by vinokurig** [comment]
QA in progress
