### PR TITLE
Fix NPE and NumberFormatException in some cases

### LINKED ISSUE #11134: Cannot create workspace from 'Java Theia on OpenShift' stack
**Reproduction steps:**
From **Dashboard** try to create a workspace from the '**Java Theia on OpenShift**' stack.

**Actual result:**
Workspace was not created. There is an error notification(see screenshot below).

**Che version**: 6.11.0-SNAPSHOT
**OS and version:** Fedora 28
**Browser:** Chrome 69.0
**Failed selenium test:** CreateWorkspaceFromJavaTheiaOpenshiftStackTest

**Additional information:**
* Problem can be reliably reproduced, doesn't happen randomly: [Yes]
* See the attachment:

**Screencast:**
screencast-che-eclipse-che 172 19 20 234 nip io-2018 09 10-10-27-08

**Screenshot:**
selection_117

**Browser console logs:**
```
2018-09-10 12:26:16,317 WARNING http://keycloak-eclipse-che.172.29.4.150.nip.io/auth/realms/che/protocol/openid-connect/auth?client_id=che-public&redirect_uri=http%3A%2F%2Fche-eclipse-che.172.29.4.150.nip.io%2Fdashboard%2F&state=1b8948e4-5902-4778-8683-4eed5491876c&nonce=97ce01fd-befa-464b-bd1b-9aa49880cc5f&response_mode=fragment&response_type=code&scope=openid - This page includes a password or credit card input in a non-secure context. A warning has been added to the URL bar. For more information, see https://goo.gl/zmWq3m.

2018-09-10 12:26:17,575 INFO http://keycloak-eclipse-che.172.29.4.150.nip.io/auth/js/keycloak.js 684:28 "[KEYCLOAK] Estimated time difference between browser and server is 0 seconds"

2018-09-10 12:26:17,845 WARNING http://che-eclipse-che.172.29.4.150.nip.io/dashboard/scripts/vendor-73784b1bca.js 74:23452 "You are using the ngTouch module. \nAngular Material already has mobile click, tap, and swipe support... \nngTouch is not supported with Angular Material!"

2018-09-10 12:26:17,970 WARNING http://che-eclipse-che.172.29.4.150.nip.io/dashboard/scripts/vendor-73784b1bca.js 74:23452 "Markup '\u003Cmd-button flex>\u003C/md-button>' may not work as expected in IE Browsers. Consult 'https://github.com/philipwalton/flexbugs#9-some-html-elements-cant-be-flex-containers' for details."

2018-09-10 12:26:17,973 WARNING http://che-eclipse-che.172.29.4.150.nip.io/dashboard/scripts/vendor-73784b1bca.js 74:23452 "Markup '\u003Cmd-button flex>\u003C/md-button>' may not work as expected in IE Browsers. Consult 'https://github.com/philipwalton/flexbugs#9-some-html-elements-cant-be-flex-containers' for details."

2018-09-10 12:26:17,976 WARNING http://che-eclipse-che.172.29.4.150.nip.io/dashboard/scripts/vendor-73784b1bca.js 74:23452 "Markup '\u003Cmd-button flex>\u003C/md-button>' may not work as expected in IE Browsers. Consult 'https://github.com/philipwalton/flexbugs#9-some-html-elements-cant-be-flex-containers' for details."

2018-09-10 12:26:17,977 WARNING http://che-eclipse-che.172.29.4.150.nip.io/dashboard/scripts/vendor-73784b1bca.js 74:23452 "Markup '\u003Cmd-button flex>\u003C/md-button>' may not work as expected in IE Browsers. Consult 'https://github.com/philipwalton/flexbugs#9-some-html-elements-cant-be-flex-containers' for details."

2018-09-10 12:26:17,997 WARNING http://che-eclipse-che.172.29.4.150.nip.io/dashboard/scripts/vendor-73784b1bca.js 74:23452 "Markup '\u003Cmd-button flex>\u003C/md-button>' may not work as expected in IE Browsers. Consult 'https://github.com/philipwalton/flexbugs#9-some-html-elements-cant-be-flex-containers' for details."

2018-09-10 12:26:17,997 WARNING http://che-eclipse-che.172.29.4.150.nip.io/dashboard/scripts/vendor-73784b1bca.js 74:23452 "Markup '\u003Cmd-button flex>\u003C/md-button>' may not work as expected in IE Browsers. Consult 'https://github.com/philipwalton/flexbugs#9-some-html-elements-cant-be-flex-containers' for details."

2018-09-10 12:26:17,998 WARNING http://che-eclipse-che.172.29.4.150.nip.io/dashboard/scripts/vendor-73784b1bca.js 74:23452 "Markup '\u003Cmd-button flex>\u003C/md-button>' may not work as expected in IE Browsers. Consult 'https://github.com/philipwalton/flexbugs#9-some-html-elements-cant-be-flex-containers' for details."

2018-09-10 12:26:17,998 WARNING http://che-eclipse-che.172.29.4.150.nip.io/dashboard/scripts/vendor-73784b1bca.js 74:23452 "Markup '\u003Cmd-button flex>\u003C/md-button>' may not work as expected in IE Browsers. Consult 'https://github.com/philipwalton/flexbugs#9-some-html-elements-cant-be-flex-containers' for details."

2018-09-10 12:26:18,066 WARNING http://che-eclipse-che.172.29.4.150.nip.io/dashboard/scripts/vendor-73784b1bca.js 74:23452 "Markup '\u003Cmd-button flex>\u003C/md-button>' may not work as expected in IE Browsers. Consult 'https://github.com/philipwalton/flexbugs#9-some-html-elements-cant-be-flex-containers' for details."

2018-09-10 12:26:18,066 WARNING http://che-eclipse-che.172.29.4.150.nip.io/dashboard/scripts/vendor-73784b1bca.js 74:23452 "Markup '\u003Cmd-button flex>\u003C/md-button>' may not work as expected in IE Browsers. Consult 'https://github.com/philipwalton/flexbugs#9-some-html-elements-cant-be-flex-containers' for details."

2018-09-10 12:26:18,077 WARNING http://che-eclipse-che.172.29.4.150.nip.io/dashboard/scripts/vendor-73784b1bca.js 74:23452 "Markup '\u003Cmd-button flex>\u003C/md-button>' may not work as expected in IE Browsers. Consult 'https://github.com/philipwalton/flexbugs#9-some-html-elements-cant-be-flex-containers' for details."

2018-09-10 12:26:18,456 INFO http://che-eclipse-che.172.29.4.150.nip.io/dashboard/scripts/vendor-73784b1bca.js 74:23452 "Preloading IDE javascript"

2018-09-10 12:26:18,470 SEVERE http://che-eclipse-che.172.29.4.150.nip.io/api/permissions/system - Failed to load resource: the server responded with a status of 404 ()

2018-09-10 12:26:18,507 SEVERE http://che-eclipse-che.172.29.4.150.nip.io/api/oauth/ - Failed to load resource: the server responded with a status of 403 ()

2018-09-10 12:26:18,577 SEVERE http://che-eclipse-che.172.29.4.150.nip.io/api/organization/find?name=user1536537067666 - Failed to load resource: the server responded with a status of 404 ()

2018-09-10 12:26:18,622 SEVERE https://api.github.com/user - Failed to load resource: the server responded with a status of 401 (Unauthorized)

2018-09-10 12:26:21,557 SEVERE https://api.github.com/user - Failed to load resource: the server responded with a status of 401 (Unauthorized)

2018-09-10 12:26:24,354 SEVERE http://che-eclipse-che.172.29.4.150.nip.io/api/workspace?namespace=user1536537067666&attribute=stackId:java-theia-openshift - Failed to load resource: the server responded with a status of 500 ()
```

### PR DESCRIPTION
**Pull request by garagatyi**
### What does this PR do?
Fix NPE on the start of a workspace created from the Theia stack.
Fix NumberFormatException when a machine doesn't have memory
property.

### What issues does this PR fix or reference?
Fixes #11134

### CODE REVIEW

File: infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/limits/ram/RamLimitProvisioner.java [hunk 1]
```diff
@@ -39,7 +39,10 @@ public void provision(KubernetesEnvironment k8sEnv, RuntimeIdentity identity)
       for (Container container : pod.getSpec().getContainers()) {
         final Map<String, String> attributes =
             machines.get(machineName(pod, container)).getAttributes();
-        Containers.addRamLimit(container, Long.parseLong(attributes.get(MEMORY_LIMIT_ATTRIBUTE)));
+        String memoryLimitAttribute = attributes.get(MEMORY_LIMIT_ATTRIBUTE);
+        if (memoryLimitAttribute != null) {
+          Containers.addRamLimit(container, Long.parseLong(memoryLimitAttribute));
```
Comment (sleshchenko) [inline infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/limits/ram/RamLimitProvisioner.java:44]: It's like an unusual case since we have configuration properties for configuring default values for machines memory if they are not specified explicitly. Should it be logged as a warning?

**Review by sleshchenko — APPROVED** [review]
LGTM

File: infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/limits/ram/RamLimitProvisioner.java (hunk 1 above)
Comment (sleshchenko) [reply infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/provision/limits/ram/RamLimitProvisioner.java:44]: Makes sense. Ok to me leave it as it is
