### PR TITLE
Fix kc deploy on openshift

### LINKED ISSUE #8320: fix che multi user deployment on ocp
today we have deployment issue while we deploy che multiuser to ocp, due to this issue we have first boot of KC pod failed and treat it as "normal behavior"  which not good.
This issue happen because to start KC pod it need CHE pod route while CHE pod also depends on KC.

### PR DESCRIPTION
**Pull request by riuvshin**
Makes deploy of CHE multi-user to openshift linear and stable. Before these changes we had situation where KC pod was always failing for the first time due to circular dependency between CHE and KC pods.

fixes: https://github.com/eclipse/che/issues/8320

### CODE REVIEW

**Review by sleshchenko — APPROVED** [review]
Good job!

File: dockerfiles/init/modules/openshift/files/scripts/deploy_che.sh [hunk 1]
```diff
@@ -429,10 +471,6 @@ echo "[CHE] Deploying Che on ${OPENSHIFT_FLAVOR} (image ${CHE_IMAGE})"
 get_che_pod_config | oc apply --force=true -f -
 echo
 
-if [ "${CHE_DEDICATED_KEYCLOAK}" == "true" ]; then
-  "${COMMAND_DIR}"/multi-user/configure_and_start_keycloak.sh
```
Comment (garagatyi) [inline dockerfiles/init/modules/openshift/files/scripts/deploy_che.sh:433]: Is it possible not to run keycloak now?

File: dockerfiles/init/modules/openshift/files/scripts/deploy_che.sh [hunk 2]
```diff
@@ -312,6 +311,49 @@ else
     exit 1
 fi
 
+# -------------------------------------------------------------
+# create CHE service and route
+# -------------------------------------------------------------
+echo "[CHE] Creating serviceaccount, service and route for CHE pod"
+ echo "apiVersion: v1
```
Comment (benoitf) [inline dockerfiles/init/modules/openshift/files/scripts/deploy_che.sh:318]: it looks strange to have yaml content in a shell script and not in its own yml file

Comment (riuvshin) [reply dockerfiles/init/modules/openshift/files/scripts/deploy_che.sh:318]: we have a lot of that already, but yeah a I completely agree with that. Some times it is need to be able to use ENV vars for that yaml

Comment (benoitf) [reply dockerfiles/init/modules/openshift/files/scripts/deploy_che.sh:318]: but there are some sed commands for that no ?

Comment (riuvshin) [reply dockerfiles/init/modules/openshift/files/scripts/deploy_che.sh:318]: no, no sed at all.
https://github.com/eclipse/che/blob/master/dockerfiles/init/modules/openshift/files/scripts/deploy_che.sh#L391-L400
https://github.com/eclipse/che/blob/master/dockerfiles/init/modules/openshift/files/scripts/multi-user/deploy_postgres_and_keycloak.sh#L25-L38
https://github.com/eclipse/che/blob/master/dockerfiles/init/modules/openshift/files/scripts/multi-user/deploy_postgres_only.sh

we have a lot of that, I'm not saying that this is good, but nothing new.

File: dockerfiles/init/modules/openshift/files/scripts/deploy_che.sh (hunk 1 above)
Comment (riuvshin) [reply dockerfiles/init/modules/openshift/files/scripts/deploy_che.sh:433]: not sure I got the question, that section that I;ve removed was used to run KC after it failed first time now we don;t need that at all as it will start up normally with first attempt

File: dockerfiles/init/modules/openshift/files/scripts/deploy_che.sh [hunk 3]
```diff
@@ -245,8 +245,7 @@ CHE_CONFIG_FILE_PATH=${CHE_CONFIG_FILE_PATH:-${DEFAULT_CHE_CONFIG_FILE_PATH}}
 cat "${CHE_DEPLOYMENT_FILE_PATH}" | \
     sed "s/          image:.*/          image: \"${CHE_IMAGE_SANITIZED}\"/" | \
     sed "s/          imagePullPolicy:.*/          imagePullPolicy: \"${IMAGE_PULL_POLICY}\"/" | \
-    inject_che_config "#CHE_MASTER_CONFIG" "${CHE_CONFIG_FILE_PATH}" | \
-    if [ "${ENABLE_SSL}" == "false" ]; then grep -v -e "tls:" -e "insecureEdgeTerminationPolicy: Redirect" -e "termination: edge" ; else cat -; fi #| \
+    inject_che_config "#CHE_MASTER_CONFIG" "${CHE_CONFIG_FILE_PATH}"
```
[the remark this answers is not in the document]
Comment (riuvshin) [reply dockerfiles/init/modules/openshift/files/scripts/deploy_che.sh:248]: sorry, but I don;t see that to align here...

File: dockerfiles/init/modules/openshift/files/scripts/deploy_che.sh (hunk 1 above)
Comment (riuvshin) [reply dockerfiles/init/modules/openshift/files/scripts/deploy_che.sh:433]: so yes it is possible not to run KC here because KC is already started at this moment, and even CHE deployed. that part was needed to trigger KC run after it failed for the first time and CHE is already deployed but now KC is already fully started before CHE deploy

File: dockerfiles/init/modules/openshift/files/scripts/deploy_che.sh (hunk 3 above)
[the remark this answers is not in the document]
Comment (garagatyi) [reply dockerfiles/init/modules/openshift/files/scripts/deploy_che.sh:248]: I mean the function you are changing. It is not aligned properly.

File: dockerfiles/init/modules/openshift/files/scripts/deploy_che.sh (hunk 2 above)
Comment (garagatyi) [reply dockerfiles/init/modules/openshift/files/scripts/deploy_che.sh:318]: I think that the true way is to put everything into one deployment config, but since we are not there I'm OK to do this approach.
@riuvshin please, consider reworking everything to deployment config file(s) in the further improvements.

**Review by garagatyi — APPROVED** [review]

File: dockerfiles/init/modules/openshift/files/scripts/deploy_che.sh (hunk 2 above)
Comment (riuvshin) [reply dockerfiles/init/modules/openshift/files/scripts/deploy_che.sh:318]: yeah, sigle DC that is definitely a proper way, but yes we are far from there and we will go that way.

Comment (riuvshin) [reply dockerfiles/init/modules/openshift/files/scripts/deploy_che.sh:318]: @benoitf WDYT?

**Review by benoitf — APPROVED** [review]
