### PR TITLE
Fixes #18065 - Handle the mixed endpoints correctly with singlehost strategy (attempt 2)

### LINKED ISSUE #18065: Secure endpoints with requireSubdomain don't work in singlehost mode
### Describe the bug
When declaring endpoints, one can require them to be on subdomains. This is the **default** behavior for endpoints in the devfile components and can be configured in plugins using the `requireSubdomain: true` attribute in the meta.yaml of plugins.

Such endpoints do not function properly when they are also `secure` and che server is in the singlehost mode.

The are at least 3 things that are problematic:

* HTTP only does not make sense together with "secure"
* Apart from the fact that http only subdomains don't make sense with secure, it also makes any XHR calls fail because code loaded using HTTPS cannot make XHR requests for http only endpoints. This breaks our plugins, because they are called dynamically from within Theia, which is loaded through a secure endpoint itself.
* JWT proxy creates incorrect redirects, because it currently doesn't take into account the possibility of subdomain endpoints in singlehost mode at all.

### Che version
 - nightly

### Steps to reproduce
1. Create a devfile from the sample below
1. Start the "Start Development Mode" command
1. Once the command has started the user app, click on the preview URL under the command
1. Observe the auth error in the new browser tab.

### Expected behavior
When `secure`, the endpoint should be acessible over https and the requests should be routed through JWT proxy correctly.

### Runtime
   - [x] kubernetes (include output of `kubectl version`)
   - [x] Openshift (include output of `oc version`)
   - [x] minikube (include output of `minikube version` and `kubectl version`)
   - [x] minishift (include output of `minishift version` and `oc version`)

### Screenshots
N/A

### Additional context
Devfile to reproduce this:

```yaml
metadata:
  name: secure-endpoints-reproducer
projects:
  - name: quarkus-quickstarts
    source:
      location: 'https://github.com/quarkusio/quarkus-quickstarts.git'
      type: git
      sparseCheckoutDir: getting-started
components:
  - id: redhat/quarkus-java11/latest
    type: chePlugin
  - mountSources: true
    endpoints:
      - name: hello-greeting-endpoint
        port: 8080
        attributes:
          secure: 'true'
          cookiesAuthEnabled: 'true'
    memoryLimit: 4927M
    type: dockerimage
    volumes:
      - name: m2
        containerPath: /home/user/.m2
    alias: centos-quarkus-maven
    image: 'quay.io/eclipse/che-quarkus:nightly'
    env:
      - value: >-
          -XX:MaxRAMPercentage=50.0 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10
          -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4
          -XX:AdaptiveSizePolicyWeight=90 -Dsun.zip.disableMemoryMapping=true
          -Xms20m -Djava.security.egd=file:/dev/./urandom -Duser.home=/home/user
        name: JAVA_OPTS
      - value: $(JAVA_OPTS)
        name: MAVEN_OPTS
  - mountSources: true
    endpoints:
      - name: hello-greeting-endpoint
        port: 8080
        attributes:
          path: /hello/greeting/che-user
    command:
      - tail
    args:
      - '-f'
      - /dev/null
    memoryLimit: 32M
    type: dockerimage
    alias: ubi-minimal
    image: registry.access.redhat.com/ubi8/ubi-minimal
apiVersion: 1.0.0
commands:
  - name: Package
    actions:
      - workdir: '${CHE_PROJECTS_ROOT}/quarkus-quickstarts/getting-started'
        type: exec
        command: ./mvnw package
        component: centos-quarkus-maven
  - name: Start Development mode (Hot reload + debug)
    actions:
      - workdir: '${CHE_PROJECTS_ROOT}/quarkus-quickstarts/getting-started'
        type: exec
        command: './mvnw compile quarkus:dev'
        component: centos-quarkus-maven
  - name: Package Native
    actions:
      - workdir: '${CHE_PROJECTS_ROOT}/quarkus-quickstarts/getting-started'
        type: exec
        command: ./mvnw package -Dnative -Dmaven.test.skip
        component: centos-quarkus-maven
  - name: Start Native
    actions:
      - workdir: '${CHE_PROJECTS_ROOT}/quarkus-quickstarts/getting-started/target'
        type: exec
        command: ./getting-started-1.0-SNAPSHOT-runner
        component: ubi-minimal
  - name: Attach remote debugger
    actions:
      - referenceContent: |
          {
            "version": "0.2.0",
            "configurations": [
              {
                "type": "java",
                "request": "attach",
                "name": "Attach to Remote Quarkus App",
                "hostName": "localhost",
                "port": 5005
              }
            ]
          }
        type: vscode-launch
```

### PR DESCRIPTION
**Pull request by metlos**
### What does this PR do?
This is a second attempt to fix #18065. This differs from the original #18121 by injecting the `ServiceExposureStrategyProvider` into `JwtProxyProvisioner` and `PassthroughProxyProvisioner` and using that to pick the configured exposure strategy + the bound multi-host strategy. This makes sure that we pick the correct multi-host strategy implementation based on the infrastructure.

This then avoids the problem reported in #18157.

### What issues does this PR fix or reference?
#18065 #18157 

### How to test this PR?
See #18121 for the repro steps

There is a test che-server image built from this PR: `quay.io/lkrejci/che-server:issue-18065`
### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [x] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [x] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

File: infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/external/ServiceExposureStrategyProvider.java [hunk 1]
```diff
@@ -38,10 +39,22 @@ public ServiceExposureStrategyProvider(
...
+              + " mandatory.");
+    }
   }
 
   @Override
   public ExternalServiceExposureStrategy get() {
     return namingStrategy;
   }
+
+  public ExternalServiceExposureStrategy getMultiHost() {
```
Comment (mshaposhnik) [inline infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/external/ServiceExposureStrategyProvider.java]: `getMultiHostStrategy` maybe? and brief javadoc...

**Review by mshaposhnik — APPROVED** [review]

File: infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/external/ServiceExposureStrategyProvider.java (hunk 1 above)
Comment (metlos) [reply infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/external/ServiceExposureStrategyProvider.java]: :+1:

**Review by skabashnyuk — APPROVED** [review]
tested `quay.io/lkrejci/che-server:issue-18065`.
Works well with single host and reproduction steps from https://github.com/eclipse/che/pull/18121
