### PR TITLE
fix: make failing e2e tests to create screenshot

### LINKED ISSUE #22529: Failing e2e tests does not create screenshot
### Describe the bug

When running `export USERSTORY=SmokeTest && npm run test` to run the smoke tests, if there is a test failure, there are no [screenshot, pagesource, or browserlog](https://github.com/eclipse/che/blob/74f10465b196d7b752c68c50b8d69b10135e8750/tests/e2e/utils/CheReporter.ts#L140-L142) files in the reports folder.

Here is the terminal output: [log](https://gist.github.com/dkwon17/dee972a4ce2126d95ec32d803b0b84f8)

### Che version

7.74@latest

### Steps to reproduce

1. Checkout this branch (this contains a smoke test that will always fail) https://github.com/dkwon17/che/tree/failSmoke
2. Set env variables:
```
export TS_SELENIUM_BASE_URL=<baseurl>
export TS_SELENIUM_OCP_USERNAME=<username>
export TS_SELENIUM_OCP_PASSWORD=<password>
```
3. Run `cd `tests/e2e` 
4. Run `export USERSTORY=SmokeTest && npm run test`
5. After smoke test fails, check the `tests/e2e/reports` folder to verify that there is no screenshot, pagesource file or browser log file

### Expected behavior

I expected a screenshot, pagesource file and browser log file

### Runtime

OpenShift

### Screenshots

_No response_

### Installation method

other (please specify in additional context)

### Environment

macOS

### Eclipse Che Logs

_No response_

### Additional context

I noticed the screenshot is created (but no pagesource, or browserlog file) if the `driverHelper` is retrieved with `e2eContainer.get` like so: https://github.com/eclipse/che/blob/41d1364f679779f61e3d17f248bcb5de260c22a4/tests/e2e/utils/CheReporter.ts#L28, instead of [constructor injection](https://github.com/eclipse/che/blob/74f10465b196d7b752c68c50b8d69b10135e8750/tests/e2e/utils/CheReporter.ts#L37)

### PR DESCRIPTION
**Pull request by nallikaea**
### What does this PR do?
fix #22529 

### Screenshot/screencast of this PR

image

### What issues does this PR fix or reference?

 #22529 

### How to test this PR?

`export USERSRORY=SmokeTest && npm run test
`
### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [x] [Tests are covering the bugfix or new feature ](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix-or-new-feature)
- [x] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [x] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

File: tests/e2e/utils/CheReporter.ts [hunk 1]
```diff
@@ -158,14 +153,12 @@ class CheReporter extends mocha.reporters.Spec {
...
-			screenshotStream.write(Buffer.from(screenshot, 'base64'));
-			screenshotStream.end();
+			screenshotStream.write(Buffer.from(screenshot, 'base64'), (): WriteStream => screenshotStream.end());
 
 			// take page source and write to file
 			const pageSource: string = await this.driverHelper.getDriver().getPageSource();
 			const pageSourceStream: WriteStream = fs.createWriteStream(pageSourceFileName);
-			pageSourceStream.write(Buffer.from(pageSource));
-			pageSourceStream.end();
+			pageSourceStream.write(Buffer.from(pageSource), (): WriteStream => pageSourceStream.end());
```
Comment (dkwon17) [inline tests/e2e/utils/CheReporter.ts]: I am getting an error when I run `npm run test` because of `WriteStream` type:

```
Generating index.ts file...
utils/CheReporter.ts:156:81 - error TS2322: Type 'void' is not assignable to type 'WriteStream'.

156    screenshotStream.write(Buffer.from(screenshot, 'base64'), (): WriteStream => screenshotStream.end());
                                                                                    ~~~~~~~~~~~~~~~~~~~~~~

utils/CheReporter.ts:161:71 - error TS2322: Type 'void' is not assignable to type 'WriteStream'.

161    pageSourceStream.write(Buffer.from(pageSource), (): WriteStream => pageSourceStream.end());
                                                                          ~~~~~~~~~~~~~~~~~~~~~~


Found 2 errors in the same file, starting at: utils/CheReporter.ts:156
```

**Review by dkwon17 — COMMENTED** [review]
Other than the error, it is working on my end:

image


Thank you for the quick fix!

File: tests/e2e/utils/CheReporter.ts (hunk 1 above)
Comment (nallikaea) [reply tests/e2e/utils/CheReporter.ts]: indeed 
updated hasky pre-commit hook to prevent this kind of errors

**Review by dmytro-ndp — APPROVED** [review]
looks good to merge
