### PR TITLE
Fix handling of error status of a workspace 

### LINKED ISSUE #13209: workspace-loader doesn't recognize when workspace start fails immediately after start request is sent
### Description
When because of some reason workspace start request succeeds but start itself fails immediately after that wsmaster send event with error to subscribed websocket clients.
But workspace-loader doesn't receive it because it subscribes only after that message was already sent.
Which leads to a infinitely running loading screen with no error shown
image

It seems that workspace-loader subscribes to workspace status event after sending workspace start request, not before that.

### Reproduction Steps

**OS and version:**    

**Diagnostics:**

### LINKED ISSUE #13681: At the launch of the workspace, the IDE "GWT" is loaded instead of "Theia" IDE
### Reproduction Steps
 - Create the workspace by devfile with defined "Theia" IDE or by stack which defined on dashboard
 - Wait until workspace is started
 - Pay attention that "GWT" IDE has been loaded
 - If go to dashboard and load workspace again the "Theia" IDE will be loaded

**Expected behavior:**
The "Theia" IDE is loaded

**Observed behavior:**
The "GWT" IDE is loaded

**Attachment:**
Screenshot from 2019-07-03 10-22-34

**OS and version:**    
Che 7.0.0-rc-3.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by akurinnoy**
### What does this PR do?

This PR fixes bug when workspace-loader is not able to handle an error status which is set immediately after workspace has been started.

### What issues does this PR fix or reference?

fix https://github.com/eclipse/che/issues/13209
fix https://github.com/eclipse/che/issues/13681

### CODE REVIEW

**Comment by akurinnoy** [comment]
ci-test

**Comment by l0rd** [comment]
@akurinnoy that doesn't look related to any issue included in the endgame issue. I think you are aware that unfortunately we cannot merge any issue that is not related to GA right now. Setting label `do-not-merge`.

**Comment by l0rd** [comment]
@akurinnoy I am removing label `do-not-merge/hold`. Can you rebase please?

**Comment by akurinnoy** [comment]
@l0rd sure, thanks!

**Comment by SkorikSergey** [comment]
ci-build

**Comment by akurinnoy** [comment]
ci-test

File: workspace-loader/src/workspace-loader.ts [hunk 1]
```diff
@@ -83,47 +87,49 @@ export class WorkspaceLoader {
...
-            }));
+        const requestWithAuth = await this.setAuthorizationHeader(request);
+        return new Promise<che.workspace.Workspace>((resolve, reject) => {
+            requestWithAuth.send();
+            requestWithAuth.onreadystatechange = () => {
+                if (requestWithAuth.readyState !== 4) {
+                    return;
+                }
+                if (requestWithAuth.status !== 200) {
+                    reject(new Error('Failed to start the workspace: "' + this.getRequestErrorMessage(requestWithAuth) + '"'));
```
Comment (olexii4) [inline workspace-loader/src/workspace-loader.ts]: Maybe 

```
 `Failed to start the workspace: "${this.getRequestErrorMessage(requestWithAuth)}"`
```

File: workspace-loader/src/workspace-loader.ts [hunk 2]
```diff
@@ -83,47 +87,49 @@ export class WorkspaceLoader {
...
-            }));
+        const requestWithAuth = await this.setAuthorizationHeader(request);
+        return new Promise<che.workspace.Workspace>((resolve, reject) => {
+            requestWithAuth.send();
+            requestWithAuth.onreadystatechange = () => {
+                if (requestWithAuth.readyState !== 4) {
+                    return;
+                }
+                if (requestWithAuth.status !== 200) {
+                    reject(new Error('Failed to get the workspace: "' + this.getRequestErrorMessage(requestWithAuth) + '"'));
```
Comment (olexii4) [inline workspace-loader/src/workspace-loader.ts]: Maybe 
```
`ailed to get the workspace: "${this.getRequestErrorMessage(requestWithAuth)}"`
```

**Comment by olexii4** [comment]
LGTM

**Review by olexii4 — APPROVED** [review]

**Review by mmorhun — APPROVED** [review]

**Review by AndrienkoAleksandr — APPROVED** [review]
