### PR TITLE
Disable autosave on Devfile editor page

### LINKED ISSUE #13982: Dashboard: While editing a devfile of a workspace, user is constantly interrupted by the auto save
### Describe the bug
Editing the devfile of an existing workspace from the dashboard is a nightmare.
It is not possible to edit a command and being interrupted by the auto save which is not doing it silently: while the user is typing it is saving, reformatting, scrolling and undoing what the user had typed few millisecond before.

### Che version

 - [ ] latest
 - [x] 7.0.0-next
 - [ ] other: please specify

### Runtime
   - [ ] kubernetes (include output of `kubectl version`) 
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl 
   - [ ] che-operator 
   - [ ] minishift-addon
   - [ ] I don't know

### Environment
   - [ ] my computer 
       - [ ] Windows
       - [x] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify) 
   - [ ] other: please specify

### PR DESCRIPTION
**Pull request by akurinnoy**
Signed-off-by: Oleksii Kurinnyi <okurinny@redhat.com>

### What does this PR do?

This PR disables autosave feature on devfile editor page. 

Initially, autosave was added in order not to lose unsaved workspace configuration changes, mainly because of going to another Dashboard page. Now, if workspace has unsaved changes, user is not able to go to another Dashboard page nor start/stop workspace.

#### Demo

Screen Recording 2019-10-17 at 11 28 58 2019-10-17 12_06_13

### What issues does this PR fix or reference?

fixes https://github.com/eclipse/che/issues/13982

### CODE REVIEW

File: dashboard/src/app/workspaces/workspace-details/devfile/workspace-devfile-editor.controller.ts [hunk 1]
```diff
@@ -48,70 +50,74 @@ export class WorkspaceDevfileEditorController {
...
-      this.devfileYaml = jsyaml.dump(this.workspaceDevfile);
-      const validateOnly = true;
-      this.onChange(validateOnly);
     }, true);
   }
 
-  $onInit(): void { }
+  $onInit(): void {
+    this.devfileYaml = jsyaml.safeDump(this.workspaceDevfile);
+    this.initialDevfileYaml = this.devfileYaml;
```
Comment (olexii4) [inline dashboard/src/app/workspaces/workspace-details/devfile/workspace-devfile-editor.controller.ts]: Unused local variable  'this.initialDevfileYaml'.

**Comment by akurinnoy** [comment]
ci-test

**Comment by akurinnoy** [comment]
@slemeur 
could you have a look at the demo and give your feedback?

**Review by olexii4 — APPROVED** [review]

**Comment by SkorikSergey** [comment]
crw-ci-test

**Comment by SkorikSergey** [comment]
ci-build

**Comment by SkorikSergey** [comment]
Selenium tests execution on Eclipse Che Multiuser on OCP (https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/2747//Selenium_20tests_20report/) doesn't show any regression against this Pull request. Failed ```RenameWorkspaceTest``` selenium test will be adapted according to autosave disabling.

**Review by SkorikSergey — APPROVED** [review]

**Comment by akurinnoy** [comment]
ci-build

**Comment by akurinnoy** [comment]
crw-ci-test

**Comment by akurinnoy** [comment]
ci-build

**Comment by akurinnoy** [comment]
ci-build

**Comment by akurinnoy** [comment]
ci-test

**Comment by SkorikSergey** [comment]
ci-test

**Review by slemeur — APPROVED** [review]
