### PR TITLE
Disable scheduling of methods annotated with @ScheduleRate/@ScheduleDelay if period/delay is negative

### LINKED ISSUE #6383: Starting a second container of eclipse/che will kill all the workspaces container of the first one
I'm trying to run 2 che-server in the same docker engine using the CLI. If I start a second che-server, the che launcher is killing all the workspaces started by the first one.
This issue is very annoying when trying to launch another che instance from a che workspace (che in che)

**Reproduction Steps:**
1. Start a first che-server

        docker run -t --rm  -v /var/run/docker.sock:/var/run/docker.sock -v /home/sutan/che-data:/data eclipse/che:nightly

2. Create and start a workspace from this new che-server
3. Start another che-server with different name and port

        docker run --rm -t -v /var/run/docker.sock:/var/run/docker.sock -v /home/sutan/data-dev:/data -e CHE_CONTAINER=che-dev -e CHE_PORT=8081 eclipse/che:nightly start

4. Then, the workspace created by the first che-server is killed

**OS and version:**    
RHEL 7

### PR DESCRIPTION
**Pull request by sunix**
### What does this PR do?
Disable scheduling of methods annotated with @ScheduleRate/@ScheduleDelay if period/delay is negative

Thanks to this PR, we can fix #6383 by setting  `che.docker.cleanup_period_min=-1`

### CODE REVIEW

**Comment by garagatyi** [comment]
+1

**Review by benoitf — APPROVED** [review]

File: core/commons/che-core-commons-schedule/src/main/java/org/eclipse/che/commons/schedule/ScheduleDelay.java [hunk 1]
```diff
@@ -42,6 +42,9 @@
   /** @return - name of configuration parameter for initialDelay */
   String initialDelayParameterName() default "";
 
-  /** @return - name of configuration parameter for delay */
+  /**
+   * @return - name of configuration parameter for delay. A negative delay value will disable the
```
Comment (garagatyi) [inline core/commons/che-core-commons-schedule/src/main/java/org/eclipse/che/commons/schedule/ScheduleDelay.java]: it is rather non-positive than negative

Comment (sunix) [reply core/commons/che-core-commons-schedule/src/main/java/org/eclipse/che/commons/schedule/ScheduleDelay.java]: right :+1:

**Review by skabashnyuk — APPROVED** [review]
Please sync with @slemeur to check if we need some docs or release notes changes.

**Comment by skabashnyuk** [comment]
Couple of words here https://github.com/eclipse/che/blob/master/core/commons/che-core-commons-schedule/README.md would be nice too.

**Comment by sunix** [comment]
@skabashnyuk @garagatyi I've updated the PR with your feedback

**Comment by garagatyi** [comment]
Don't want to be PITA by saying it so late but have you considered using just zero instead of non-positive value? A single value for disabling feature is easier for understanding than a range.

**Comment by sunix** [comment]
@garagatyi I think a single value would confuse people.

**Review by garagatyi — APPROVED** [review]

**Comment by garagatyi** [comment]
OK

**Review by skabashnyuk — APPROVED** [review]

**Review by slemeur — APPROVED** [review]
ok for me
