### PR TITLE
CHE-10540: stop progress on websocket error

### LINKED ISSUE #10540: Make workspace-loader (or UD) show an error received from websocket on workspace start failure
### Description
When workspace start fails after some time workspace-loader and UD receive the message with the error, but provide UX that might be not clear to some users:
- There is a red circle near the workspace name
- There is no error shown
- The workspace loading progress bar doesn't disappear that might make a user think that workspace is still starting  

Instead of that, it would be nice to:
- stop showing the progress bar
- show a popup with the error message and a button to restart the workspace (the same as reloading the page) 

### Reproduction Steps

**OS and version:**    

**Diagnostics:**

### PR DESCRIPTION
**Pull request by akurinnoy**
### What does this PR do?
When workspace loader starts a workspace and receives an error on websocket, then error appears and the progress bar hides.
restart2

### What issues does this PR fix or reference?
fix #10540 

#### Release Notes

N/A - bugfix

#### Docs PR

N/A - bugfix

### CODE REVIEW

File: workspace-loader/src/index.ts [hunk 1]
```diff
@@ -225,33 +208,34 @@ export class WorkspaceLoader {
...
-            return Promise.reject(errorMessage);
         });
     }
 
+    getRequestErrorMessage(xhr: XMLHttpRequest): string {
+        let errorMessage;
+        try {
+            const response = JSON.parse(xhr.responseText);
+            errorMessage = response.message;
+        } catch (e) { }
```
Comment (benoitf) [inline workspace-loader/src/index.ts:226]: should we log error message/response ?

File: workspace-loader/src/index.ts [hunk 2]
```diff
@@ -322,7 +306,7 @@ export class WorkspaceLoader {
             masterApi.subscribeWorkspaceStatus(this.workspace.id,
                 (message: any) => {
                     if (message.error) {
-                        this.loader.error(message.error);
+                        reject(`Failed to run the workspace: "${message.error}"`);
```
Comment (benoitf) [inline workspace-loader/src/index.ts]: should we reject with new Error() ?

**Review by benoitf — APPROVED** [review]

File: workspace-loader/src/index.ts (hunk 1 above)
Comment (akurinnoy) [reply workspace-loader/src/index.ts:226]: It is eventually logged here https://github.com/eclipse/che/blob/389e259d7672fe57300f10ad19657076ea7f19f9/workspace-loader/src/index.ts#L145-L146

Here I only tried to get a meaningful error message to reject a workspace getting or starting promise.

File: workspace-loader/src/index.ts [hunk 3]
```diff
@@ -322,7 +306,7 @@ export class WorkspaceLoader {
...
                     } else if (message.status === 'RUNNING') {
                         resolve();
```
Comment (ashumilova) [inline workspace-loader/src/index.ts]: Can we, please, also check "runtime" is there (not null), when we have RUNNING status. If not - reject the promise. 
There is usecase, when user tries to open shared workspace, where he has no permissions on runtime.

File: workspace-loader/src/index.ts (hunk 2 above)
Comment (akurinnoy) [reply workspace-loader/src/index.ts]: Yes, it may be useful, I'll fix this.

File: workspace-loader/src/index.ts (hunk 3 above)
Comment (akurinnoy) [reply workspace-loader/src/index.ts]: sure, I'll add a fixup

Comment (sleshchenko) [reply workspace-loader/src/index.ts]: More details here https://github.com/eclipse/che/issues/10687
Maybe we can also handle second use case here when POST /workspace/WS_ID/runtime is failed

Comment (akurinnoy) [reply workspace-loader/src/index.ts]: That POST is handled here
https://github.com/eclipse/che/blob/389e259d7672fe57300f10ad19657076ea7f19f9/workspace-loader/src/index.ts#L211-L212

Comment (sleshchenko) [reply workspace-loader/src/index.ts]: Cool. I missed it because PR title and even description tell nothing about this change.

Looks like we will be able to close that issue after merge. I can recheck after merge.

Comment (akurinnoy) [reply workspace-loader/src/index.ts]: It was another PR https://github.com/eclipse/che/pull/10642 which is already merged.

Comment (sleshchenko) [reply workspace-loader/src/index.ts]: I see, thanks. 
I did find the given lines in master and you pointed commit from this PR, it's why I thought that it is introduced in this PR =)

**Review by olexii4 — APPROVED** [review]

**Review by ashumilova — APPROVED** [review]

**Review by vitaliy-guliy — APPROVED** [review]
