### PR TITLE
CHE-2331: add all containers to Che master docker network

### LINKED ISSUE #2331: Cannot launch a workspace after creation
**Reproduction Steps:**
1. Create  a workspace from the Dashboard and go to the workspace

**Expected behavior:**
The workspace should start without errors
**Observed behavior:** 
During creation the workspace we have error mesage like: 
`Could not start workspace rtetr. Reason: Start of environment default failed. Error: Timeout reached. The Che server has been unable to verify that your workspace's agent has successfully booted. Either the workspace is unreachable, the agent had an error during startup, or your workspace is starting slowly. You can configure machine.ws_agent.max_start_time_ms in Che properties to increase the timeout.``

selection_012

**Che version:**    4.8.0
**OS and version:** Che nightly image with latest changes
**But  if we use Che without docker (as tomcat) workspaces are created correct**

### PR DESCRIPTION
**Pull request by garagatyi**
### What does this PR do?

Adds all docker containers into bridge network where Che server is launched (in case it is in a container).
Also makes some cleanup.
### What issues does this PR fix or reference?

Fixes #2331 
### PR type
- [x] Minor change = no change to existing features or docs
- [ ] Major change = changes existing features or docs
### Minor change checklist
- [x] New API required? 
  No
- [x] API updated
  No
- [x] Tests provided / updated
- [x] Tests passed

### CODE REVIEW

**Comment by garagatyi** [comment]
@TylerJewell Please review changes in che.sh

File: plugins/plugin-docker/che-plugin-docker-machine/src/main/java/org/eclipse/che/plugin/docker/machine/CheInContainerNetworkProvider.java [hunk 1]
```diff
@@ -0,0 +1,45 @@
...
+@Singleton
+public class CheInContainerNetworkProvider implements Provider<Set<String>> {
+
+    private Set<String> networks;
+
+    @Inject
+    public CheInContainerNetworkProvider(@Nullable @Named("docker.che_host_network") String cheMasterNetwork) {
+        if (cheMasterNetwork == null) {
+            networks = Collections.emptySet();
+        } else {
```
Comment (skabashnyuk) [inline plugins/plugin-docker/che-plugin-docker-machine/src/main/java/org/eclipse/che/plugin/docker/machine/CheInContainerNetworkProvider.java]: firstNotNUll

**Comment by skabashnyuk** [comment]
ok
