### PR TITLE
Stabilize check of build and run application in Happy path tests

### LINKED ISSUE #19895: Happy path tests are failing on "Check the running application" step
### Describe the bug
Happy path tests failed on "Check the running application" step:
https://main-jenkins-csb-crwqe.apps.ocp4.prod.psi.redhat.com/job/Che/job/e2e/job/minikube/job/pr-check/job/che-theia-pr-check/107/console
```
13:28:51            ▼ PreviewWidget.refreshPage
13:28:51              ‣ DriverHelper.waitAndClick By(css selector, .theia-mini-browser .theia-mini-browser-refresh)
13:28:51              ‣ DriverHelper.waitVisibility By(css selector, .theia-mini-browser .theia-mini-browser-refresh)
13:28:51              ‣ DriverHelper.waitVisibility - Element is located and is visible.
13:28:51            ▼ PreviewWidget.waitAndSwitchToWidgetFrame
13:28:51              ‣ DriverHelper.waitAndSwitchToFrame By(css selector, div.theia-mini-browser iframe)
13:28:51              ‣ DriverHelper.wait (10000 milliseconds)
13:29:01      1) Check the running application
13:29:01    [ERROR] CheReporter runner.on.fail: Validation of workspace build and run Check the running application failed after 62087ms
13:29:01  
13:29:01  
13:29:01    10 passing (8m)
13:29:01    1 pending
13:29:01    1 failing
13:29:01  
13:29:01    1) Validation of workspace build and run
13:29:01         Check the running application:
13:29:01       TimeoutError: Wait timed out after 61769ms
13:29:01        at /tmp/e2e/node_modules/selenium-webdriver/lib/promise.js:2201:17
```

Google Chrome console log fragment:
> "SEVERE" "" "https://serverldcrfw0q-jwtproxy-server-4402.10.0.210.190.nip.io/vs/editor/editor.main.js 30:600 Uncaught Error: > There is no document for breakpointinput:vs.editor…@theia/plugin-ext/lib/plugin/languages.js:333:21)"
> "SEVERE" "" "https://serverldcrfw0q-jwtproxy-server-4402.10.0.210.190.nip.io/vs/editor/editor.main.js 30:600 Uncaught Error: There is no document for breakpointinput:vs.editor…@theia/plugin-ext/lib/plugin/languages.js:333:21)"
> "SEVERE" "" "https://serverldcrfw0q-jwtproxy-server-4402.10.0.210.190.nip.io/bundle.js 32:363433 "root ERROR Notification handler 'connected' failed with message: Cannot read property 'apply' of undefined""
> "SEVERE" "" "https://serverldcrfw0q-jwtproxy-server-4402.10.0.210.190.nip.io/bundle.js 2:77291 Uncaught Error: No file system provider found for scheme https"

screenshot-Check_the_running_application

Screencast:

https://user-images.githubusercontent.com/1197777/120214832-ab707680-c23d-11eb-8a4a-589cab8545d9.mp4

There was weird URL in preview widget: "**https://about:blank#blocked**"

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
Run Happy path tests.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [x] minikube 1.1.1
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Installation method
   - [x] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] Dev Sandbox (workspaces.openshift.com)
   - [x] other: CRW CCI

### Eclipse Che Logs
https://main-jenkins-csb-crwqe.apps.ocp4.prod.psi.redhat.com/job/Che/job/e2e/job/minikube/job/pr-check/job/che-theia-pr-check/107/artifact/logs-and-configs/workspace-logs/

### Additional context
Possible root cause: https://github.com/eclipse/che/issues/19910

### PR DESCRIPTION
**Pull request by dmytro-ndp**
### What does this PR do?
It is:
1. Adding timeout in Happy path tests to wait on opening application in Preview Widget.
2. Removing outdated workaround to https://github.com/eclipse/che/issues/14520
3. Adding workaround to https://github.com/eclipse/che/issues/19887
4. Using "che-e2e:next" instead of "che-e2e:nightly" in Eclipse Che E2E testing CI jobs

### Screenshot/screencast of this PR
screenshot-Check_the_running_application

### What issues does this PR fix or reference?
Closes: https://github.com/eclipse/che/issues/19895, https://github.com/eclipse/che/issues/19886
Relates: https://github.com/eclipse/che/issues/19887, https://github.com/eclipse/che/issues/19905

### How to test this PR?
Run Happy path tests

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [ ] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [x] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [ ] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Review by artaleks9 — APPROVED** [review]

File: tests/e2e/pageobjects/ide/PreviewWidget.ts [hunk 1]
```diff
@@ -86,6 +86,8 @@ export class PreviewWidget {
 
         Logger.debug(`PreviewWidget.waitContentAvailable ${contentLocator}`);
 
+        await this.driverHelper.wait(polling);   // workaround https://github.com/eclipse/che/issues/19895
```
Comment (Katka92) [inline tests/e2e/pageobjects/ide/PreviewWidget.ts]: Those hardcoded waits are not a good practice. I would instead try something from below solutions:

1. Set the environment variable `TS_SELENIUM_PREVIEW_WIDGET_DEFAULT_TIMEOUT`  (which is used directly in the `waitAndSwitchTOWidgetFrame` [method](https://github.com/eclipse/che/blob/384f90b6f07d7c3475ca9239f4f2b365e68b536c/tests/e2e/pageobjects/ide/PreviewWidget.ts#L73)) to something larger than default (10_000 ms) so it will be increased for your particular test.
2. Increase the default value of `TS_SELENIUM_PREVIEW_WIDGET_DEFAULT_TIMEOUT` [here](https://github.com/eclipse/che/blob/384f90b6f07d7c3475ca9239f4f2b365e68b536c/tests/e2e/TimeoutConstants.ts#L173), so it will be larger in every test using that method.
3. Leave the default timeout as is and add an optional timeout parameter to the `waitAndSwitchToWidgetFrame` method so the timeout can be adjusted per method call. 

If you need any help solving that issue, feel free to ping me.

Comment (Ohrimenko1988) [reply tests/e2e/pageobjects/ide/PreviewWidget.ts]: If you trying to fix a problem with a blank screen, unfortunately, a simple wait will not help.
You need to gain an application route, and if a blank screen has shown, type this route to the widget address bar.

Another way is to open the application in the browser tab instead preview widget.

Comment (Ohrimenko1988) [reply tests/e2e/pageobjects/ide/PreviewWidget.ts]: Example for using browser tab https://github.com/eclipse/che/blob/main/tests/e2e/tests/plugins/TypescriptPlugin.spec.ts#L98-L155

Comment (Katka92) [reply tests/e2e/pageobjects/ide/PreviewWidget.ts]: Interesting, just for curiosity - is it known what is the root cause of this `blank screen` problem? Is there some issue created? Thanks

Comment (Ohrimenko1988) [reply tests/e2e/pageobjects/ide/PreviewWidget.ts]: As far as I remember it was some issue about that. But I am not sure. The main problem, this problem doesn't reproduce by hands. It is something specific for automation.

Comment (dmytro-ndp) [reply tests/e2e/pageobjects/ide/PreviewWidget.ts]: @Katka92, @Ohrimenko1988: thank you for review!

@Katka92: The problem is that after switching to Preview Widget frame the test can't find "**Welcome**" message and [then instantly clicking on "refresh" button in Preview Widget, which redirects to "blank:empty" page](https://main-jenkins-csb-crwqe.apps.ocp4.prod.psi.redhat.com/job/Che/job/e2e/job/minikube/job/pr-check/job/che-theia-pr-check/137/consoleFull). 
There is an issue about broken refresh button exists https://github.com/eclipse/che/issues/19910
 
@Ohrimenko1988: actually, it has been working with simple 10 seconds wait.
E.g., you can compare:
- failed Happy path tests https://main-jenkins-csb-crwqe.apps.ocp4.prod.psi.redhat.com/job/Che/job/e2e/job/minikube/job/pr-check/job/che-theia-pr-check/137/consoleFull
- passed Happy path tests with timeout in the same PR: https://main-jenkins-csb-crwqe.apps.ocp4.prod.psi.redhat.com/job/Che/job/e2e/job/minikube/job/pr-check/job/che-theia-pr-check/143/consoleFull

IMHO, another possible "timeout less" solution in this case could be not clicking on "**Refresh**" button at all (`this.refreshPage()`), but waiting on page to be fully loaded in Preview Widget.

Comment (Katka92) [reply tests/e2e/pageobjects/ide/PreviewWidget.ts]: I've searched a little in our codebase and there is already method including this polling/attmepts mechanism: https://github.com/eclipse/che/blob/3df3228210d625b490cf16ff2a926369d6f4ec14/tests/e2e/utils/DriverHelper.ts#L63 So maybe whole this [block](https://github.com/eclipse/che/pull/19909/files#diff-e3e126311533b5946de6dbfa699df2efaa80613f43750e687fa6a377f1aee855L90-L102) can be just replaced by the method I shared. But I'm not insisting on that - if you are OK with just removing the refresh part, I'm OK.

**Review by Katka92 — APPROVED** [review]

File: tests/e2e/pageobjects/ide/PreviewWidget.ts (hunk 1 above)
Comment (Katka92) [reply tests/e2e/pageobjects/ide/PreviewWidget.ts]: And thank you @dmytro-ndp for sharing the link to the issue! :slightly_smiling_face:

**Review by Ohrimenko1988 — APPROVED** [review]

**Comment by dmytro-ndp** [comment]
[crw-ci-test]

**Comment by dmytro-ndp** [comment]
[crw-ci-test]

**Comment by dmytro-ndp** [comment]
[crw-ci-test]

**Comment by dmytro-ndp** [comment]
[crw-ci-test]

**Comment by dmytro-ndp** [comment]
[crw-ci-test]

**Comment by dmytro-ndp** [comment]
[crw-ci-test]

**Comment by dmytro-ndp** [comment]
[crw-ci-test]

**Comment by dmytro-ndp** [comment]
[crw-ci-test]

**Comment by dmytro-ndp** [comment]
[crw-ci-test]

**Comment by dmytro-ndp** [comment]
[crw-ci-test]

**Comment by dmytro-ndp** [comment]
@Katka92, @Ohrimenko1988, @artaleks9: could you, please, review new changes in https://github.com/eclipse/che/pull/19909?
Sorry for asking about it again - it had been taken more time to ensure the fix was just enough for stabilizing of Happy path tests, and I had decided to include one more fix to stabilize verification of application build https://github.com/eclipse/che/issues/19886, and to add workaround to debug flakiness https://github.com/eclipse/che/issues/19887.

**Review by Katka92 — APPROVED** [review]
