### PR TITLE
Selenium: Rework the 'WorkingWithPullConflictsTest' related to #8832

### LINKED ISSUE #7887: Investigate the session unexpectedly deleted when running selenium tests on CI job
### Description
* When the test suite is running on the CI job, sometimes there is failing test  'GitCompareTest' by reason: **_"session deleted because of page crash"_** 
* Need to investigate it and fix up

**See the report:**
page-crash

**Che version:** 6.0.0-M4
**OS and version:** Fedora 25
**Docker version:** 17.06
**API docker version:** 1.30
**Che install:** Docker container

**Additional information:**
* Related selenium test: _GitCompareTest_
* Problem can be reliably reproduced, doesn't happen randomly: [No]

**Update**: Similar error can be found here at [org.eclipse.che.selenium.git.PullRequestPluginTest.checkGitHubUserPage(PullRequestPluginTest.java:240)](https://ci.codenvycorp.com/view/qa/job/che-integration-tests-multiuser-master-ocp/57/consoleText)

**Related issue:** https://github.com/eclipse/che/issues/8100

### PR DESCRIPTION
**Pull request by artaleks9**
### What does this PR do?
* Improve and rework selenium test 'WorkingWithPullConflictsTest'
* Rename the 'WorkingWithPullConflictsTest' on the 'GitPullConflictTest'
* Delete the 'try/catch' block from the 'GitCompareTest' related to closed #7887
* Remove the 'GitCompareTest' and 'GitPullTest' from the 'CheOneThreadTestsSuite.xml' to the 'CheSuite.xml'
* Add the 'git-pull-conflict' to the projects in the resources

### What issues does this PR fix or reference?
#8832

### CODE REVIEW

File: selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/GitPullConflictTest.java [hunk 1]
```diff
@@ -0,0 +1,199 @@
...
+    projectExplorer.openItemByPath(
+        String.format("%s/%s/%s.java", PROJECT_NAME, pathToJavaFile, fileName));
+    editor.waitActive();
+    editor.deleteAllContent();
+    editor.typeTextIntoEditor(text);
+    editor.waitActive();
+    editor.waitTextIntoEditor(text);
+    editor.waitTabFileWithSavedStatus(fileName);
+  }
+
```
Comment (musienko-maxim) [inline selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/GitPullConflictTest.java]: I think ProjectServiceClient will be better for this

File: selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/GitPullConflictTest.java [hunk 2]
```diff
@@ -0,0 +1,199 @@
...
+    projectExplorer.openItemByPath(String.format("%s/%s", PROJECT_NAME, fileName));
+    editor.waitActive();
+    editor.setCursorToLine(1);
+    editor.selectLineAndDelete();
+    editor.typeTextIntoEditor(text);
+    editor.waitActive();
+    editor.waitTextIntoEditor(text);
+    editor.waitTabFileWithSavedStatus(fileName);
+  }
+
```
Comment (musienko-maxim) [inline selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/GitPullConflictTest.java]: The same about ProjectService

File: selenium/che-selenium-test/src/test/resources/projects/git-pull-conflict/src/main/webapp/index.jsp [hunk 3]
```diff
@@ -0,0 +1,15 @@
...
+    which accompanies this distribution, and is available at
+    http://www.eclipse.org/legal/epl-v10.html
+
+    Contributors:
+      Red Hat, Inc. - initial API and implementation
+
+--%>
+<%
+   response.sendRedirect("spring/hello");
+%>
```
Comment (musienko-maxim) [inline selenium/che-selenium-test/src/test/resources/projects/git-pull-conflict/src/main/webapp/index.jsp]: Add line

File: selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/GitPullConflictTest.java [hunk 4]
```diff
@@ -0,0 +1,199 @@
...
+    events.clickEventLogBtn();
+    events.waitExpectedMessage(firstMergeConflictMessage);
+
+    commitFiles();
+
+    // Make pull again and get second conflict
+    performPull();
+    events.clickEventLogBtn();
+    events.waitExpectedMessage(secondMergeConflictMessage);
+
```
Comment (musienko-maxim) [inline selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/GitPullConflictTest.java]: Why do we check 2 conflicts? 1 checking is not enough?

File: selenium/che-selenium-test/src/test/resources/projects/git-pull-conflict/src/main/webapp/index.jsp (hunk 3 above)
Comment (musienko-maxim) [reply selenium/che-selenium-test/src/test/resources/projects/git-pull-conflict/src/main/webapp/index.jsp]: We should use new project in the resources for the test? May be use already existed?

File: selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/GitPullConflictTest.java (hunk 4 above)
Comment (artaleks9) [reply selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/GitPullConflictTest.java]: by scenario we have changes in the same files locally and on GitHub, perform pull  
 1) conflict: `Checkout operation failed, the following files would be overwritten by merge: <...files....> Could not pull. Commit your changes before merging.`

then we make commit files, perform pull and have
 2) conflict: `Could not pull because a merge conflict is detected in the files:
<...files....> Automatic merge failed; fix conflicts and then commit the result.`

File: selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/GitPullConflictTest.java [hunk 5]
```diff
@@ -0,0 +1,199 @@
...
+import org.kohsuke.github.GitHub;
+import org.testng.annotations.AfterClass;
+import org.testng.annotations.BeforeClass;
+import org.testng.annotations.Test;
+
+/** @author aleksandr shmaraev */
+public class GitPullConflictTest {
+  private static final String REPO_NAME = NameGenerator.generate("PullConflictTest-", 3);
+  private static final String PROJECT_NAME = NameGenerator.generate("PullConflictProject-", 4);
+  private static final String pathToJavaFile = "src/main/java/commenttest";
```
Comment (dmytro-ndp) [inline selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/GitPullConflictTest.java]: It's constant. Capitalize, please.

File: selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/GitPullConflictTest.java [hunk 6]
```diff
@@ -0,0 +1,199 @@
...
+  private static final String COMMIT_MSG = "commit_changes";
+
+  private static final String firstMergeConflictMessage =
```
Comment (dmytro-ndp) [inline selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/GitPullConflictTest.java]: It's constant. Capitalize, please.

File: selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/GitPullConflictTest.java [hunk 7]
```diff
@@ -0,0 +1,199 @@
...
+      "Checkout operation failed, the following files would be overwritten by merge:\n"
+          + "GitPullTest.txt\n"
+          + "src/main/java/commenttest/JavaCommentsTest.java\n"
+          + "Could not pull. Commit your changes before merging.";
+
+  private static final String secondMergeConflictMessage =
```
Comment (dmytro-ndp) [inline selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/GitPullConflictTest.java]: It's constant. Capitalize, please.

File: selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/GitPullConflictTest.java [hunk 8]
```diff
@@ -0,0 +1,199 @@
...
+      "Could not pull because a merge conflict is detected in the files:\n"
+          + "GitPullTest.txt\n"
+          + "src/main/java/commenttest/JavaCommentsTest.java\n"
+          + "Automatic merge failed; fix conflicts and then commit the result.";
+
+  private static final String CHANGE_STRING_1 =
+      String.format("//first_change_%s", System.currentTimeMillis());
+
+  private static final String headConfPrefixConfMess =
```
Comment (dmytro-ndp) [inline selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/GitPullConflictTest.java]: It's constant. Capitalize, please.

File: selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/GitPullConflictTest.java [hunk 9]
```diff
@@ -0,0 +1,199 @@
...
+      "<<<<<<< HEAD\n" + "//second_change\n" + "=======\n" + CHANGE_STRING_1 + "\n" + ">>>>>>>";
```
Comment (dmytro-ndp) [inline selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/GitPullConflictTest.java]: Too many concatenations makes the value hard to read. Please, replace concatenations with one `String.format()` method invocation.

File: selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/GitPullConflictTest.java [hunk 10]
```diff
@@ -0,0 +1,199 @@
...
+  public void deleteRepo() throws IOException {
+    gitHubRepository.delete();
+  }
+
+  @Test
+  public void pullConflictsTest() throws IOException {
+    // preconditions and import the test repo
+    String javaFileChange = "JavaCommentsTest";
+    String textFileChange = "GitPullTest.txt";
+    String changeContent_2 = "//second_change";
```
Comment (dmytro-ndp) [inline selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/GitPullConflictTest.java]: we are using _camelCase_ style of variable naming. It can have name `secondChange` for example.

File: selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/GitPullConflictTest.java [hunk 11]
```diff
@@ -0,0 +1,199 @@
...
+
+  private void changeContentOnGithubSide(String pathToContent, String content) throws IOException {
+    gitHubRepository
+        .getFileContent(String.format("/%s", pathToContent))
+        .update(content, "add " + content);
+  }
+
+  private void performPull() {
+    menu.runCommand(GIT, REMOTES_TOP, PULL);
+    git.waitPullFormToOpen();
```
Comment (dmytro-ndp) [inline selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/GitPullConflictTest.java]: Please, divide operations with identical page objects, by empty rows, to improve readability.

File: selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/GitPullConflictTest.java [hunk 12]
```diff
@@ -0,0 +1,199 @@
...
+    git.clickPull();
+    git.waitPullFormToClose();
+    consoles.waitProcessInProcessConsoleTree("Git pull", LOADER_TIMEOUT_SEC);
+  }
+
+  private void commitFiles() {
+    projectExplorer.selectItem(PROJECT_NAME);
+    menu.runCommand(TestMenuCommandsConstants.Git.GIT, TestMenuCommandsConstants.Git.COMMIT);
```
Comment (dmytro-ndp) [inline selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/GitPullConflictTest.java:178]: Please, divide operations with identical page objects, by empty rows, to improve readability.

File: selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/GitPullConflictTest.java [hunk 13]
```diff
@@ -0,0 +1,199 @@
...
+    editor.deleteAllContent();
+    editor.typeTextIntoEditor(text);
+    editor.waitActive();
+    editor.waitTextIntoEditor(text);
+    editor.waitTabFileWithSavedStatus(fileName);
+  }
+
+  private void changeTextFileForTest(String fileName, String text) {
+    projectExplorer.openItemByPath(String.format("%s/%s", PROJECT_NAME, fileName));
+    editor.waitActive();
```
Comment (dmytro-ndp) [inline selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/GitPullConflictTest.java]: Please, divide operations with identical page objects, by empty rows, to improve readability.

File: selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/GitPullConflictTest.java [hunk 14]
```diff
@@ -0,0 +1,199 @@
...
+    editor.selectTabByName(textFileChange);
+    editor.waitActive();
+    editor.waitTextIntoEditor(headConfPrefixConfMess);
+  }
+
+  private void changeJavaFileForTest(String fileName, String text) {
+    projectExplorer.quickExpandWithJavaScript();
+    projectExplorer.openItemByPath(
+        String.format("%s/%s/%s.java", PROJECT_NAME, pathToJavaFile, fileName));
+    editor.waitActive();
```
Comment (dmytro-ndp) [inline selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/GitPullConflictTest.java]: Please, divide operations with identical page objects, by empty rows, to improve readability.

File: selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/GitPullConflictTest.java [hunk 15]
```diff
@@ -0,0 +1,196 @@
...
+  }
+
+  private void changeJavaFileForTest(String fileName, String text) throws Exception {
+    String path = String.format("%s/%s/%s.java", PROJECT_NAME, PATH_TO_JAVA_FILE, fileName);
+    projectExplorer.quickExpandWithJavaScript();
+    projectExplorer.openItemByPath(path);
+    editor.waitActive();
+    testProjectServiceClient.updateFile(ws.getId(), path, text);
+    editor.waitTextIntoEditor(text);
+  }
```
Comment (musienko-maxim) [inline selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/GitPullConflictTest.java]: Why we open editor after updating file by ProjectServiceClient?

File: selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/GitPullConflictTest.java [hunk 16]
```diff
@@ -0,0 +1,196 @@
...
+
+    commitFiles();
+
+    // Make pull again and get second conflict
+    performPull();
+    events.clickEventLogBtn();
+    events.waitExpectedMessage(SECOND_MERGE_CONFLICT_MESSAGE);
+
+    // Checking the message has present
+    editor.selectTabByName(javaFileChange);
```
Comment (musienko-maxim) [inline selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/GitPullConflictTest.java]: Checking the message has present -> Checking the expected message ?

File: selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/GitPullConflictTest.java [hunk 17]
```diff
@@ -0,0 +1,196 @@
...
+    // change files in the test repo on GitHub
+    changeContentOnGithubSide(
+        String.format("%s/%s.java", PATH_TO_JAVA_FILE, javaFileChange), CHANGE_STRING_1);
+    changeContentOnGithubSide(textFileChange, CHANGE_STRING_1);
+
+    // change the same files in the editor
+    changeJavaFileForTest(javaFileChange, changeContent2);
+    changeTextFileForTest(textFileChange, changeContent2);
+
+    // make pull and get the first conflict
```
Comment (musienko-maxim) [inline selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/GitPullConflictTest.java]: ```// make pull and get the first conflict ->  make pull and check the expected conflict message``` or something like that

File: selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/GitPullConflictTest.java (hunk 16 above)
Comment (dmytro-ndp) [reply selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/GitPullConflictTest.java]: Actually, we aren't checking expected message here. We are checking that expected message is presented.

File: selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/GitPullConflictTest.java (hunk 17 above)
Comment (dmytro-ndp) [reply selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/GitPullConflictTest.java]: Actually, we aren't checking expected conflict message. We are checking if conflict message which we get is the same as expected.

Comment (musienko-maxim) [reply selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/GitPullConflictTest.java]: ```make pull and get the first conflict``` looks strange as for me

File: selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/GitPullConflictTest.java (hunk 16 above)
Comment (musienko-maxim) [reply selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/git/GitPullConflictTest.java]: May be in this case: has present -> is present

**Review by musienko-maxim — APPROVED** [review]

**Review by dmytro-ndp — APPROVED** [review]
