### PR TITLE
.NET C# stacktrace support #5489

### LINKED ISSUE #5489: .NET C# stacktrace support
Che should be able to analyze and open the correct file associated with a given stacktrace. 

Probably, it's possible to process and open according source files not only for normal stacktraces, like:
```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at hwapp.ppp.PPPProgram.Main1(String[] args) in /home/zzz/projects/csharp/hwapp/ppp/PPPProgram.cs:line 18
   at hwapp.Program.Main(String[] args) in /home/zzz/projects/csharp/hwapp/Program.cs:line 10
```
but also for different WARNING and ERROR messages from .net runtime, like:
```
ppp/PPPProgram.cs(9,17): warning CS0219: The variable 'testIntValue' is assigned but its value is never used [/home/zzz/projects/csharp/hwapp/hwapp.csproj]

Program.cs(2,13): error CS0234: The type or namespace name 'ppp' does not exist in the namespace 'hwapp' (are you missing an assembly reference?) [/home/zzz/projects/csharp/hwapp/hwapp.csproj]

The build failed. Please fix the build errors and run again.
```

### LINKED ISSUE #5546: DefaultOutputCustomizer#customize() throws NumberFormatException on some inputs
The following input throw NumberFormatException on the following line:
`                int lineNumber = Integer.valueOf(text.substring(column + ":".length(), closingBracket).trim());
`

Original message:

"[STDOUT] 2017-07-06 08:58:34,647 [ForkJoinPool.commonPool-worker-3] DEBUG o.j.t.l.t.DocumentManager.findSelectedWord - Looking for word at Position 2 in 'textDocument/badWord:Warning:name:So bad!  '"

Html-Escaped (actual input to the "customize" method): 

"[STDOUT] 2017-07-06 08:58:34,647 [ForkJoinPool.commonPool-worker-3] DEBUG o.j.t.l.t.DocumentManager.findSelectedWord - Looking for word at Position 2 in &#39;textDocument/badWord:Warning:name:So bad!  &#39;"

### PR DESCRIPTION
**Pull request by vrubezhny**
Adds the possibility to click on a stacktrace and compilation error/warning message lines in order to open a specified .NET C# class in editor.

Example:
Example

Fixes #5489
Fixes #5546 

Signed-off-by: Victor Rubezhny <vrubezhny@redhat.com>

### What does this PR do?
Adds the possibility to click on a stacktrace and compilation error/warning message lines in order to open a specified .NET C# class in editor.

### What issues does this PR fix or reference?
Issue #5489
Issue #5546

#### Release Notes

This version introduces new capabilities to the .NET and C# developers. Eclipse Che, now analyzes stacktraces and compilation error/warning messages from the console to intercept files and lines references. Those references are highlighted as links, when clicked, it opens .NET C# class in editor and reveal it to the line according to the info provided in the console output line.

[Animated Gif]

The smart selection capability is available for .NET C#  stacktraces and compilation error/warning messages as well as for Java and NodeJS stacktraces at this moment.

### CODE REVIEW

**Comment by benoitf** [comment]
ci-build

**Comment by benoitf** [comment]
ci-build

File: ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/console/CSharpOutputCustomizer.java [hunk 1]
```diff
@@ -0,0 +1,187 @@
...
+
+import com.google.gwt.regexp.shared.RegExp;
+
+/**
+ * Output customizer adds an anchor link to the lines that match a .NET C#
+ * compilation error or warning message and a stack trace line pattern and
+ * installs the handler functions for the links. The handler parses the stack
+ * trace line, searches for a candidate C# file to navigate to, opens the found
+ * file in editor and reveals it to the required line and column (if available)
+ * according to the line information
```
Comment (benoitf) [inline ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/console/CSharpOutputCustomizer.java:27]: you should add the `@author` tag

File: ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/console/DefaultOutputCustomizer.java [hunk 2]
```diff
@@ -185,32 +168,73 @@ private boolean endsWith(Path path, Path relativePath) {
...
+     * @param columnNumber
      */
-    private void selectRange(EditorPartPresenter editor, int line) {
-        if (editor instanceof TextEditor) {
-            TextPosition startPosition = new TextPosition(line - 1, 0);
-            int lineOffsetStart = ((TextEditor) editor).getDocument().getLineStart(line - 1);
-            if (lineOffsetStart == -1) {
-                lineOffsetStart = 0;
-            }
+    static void openFileInEditorAndReveal(AppContext appContext, EditorAgent editorAgent, Path file,
```
Comment (benoitf) [inline ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/console/DefaultOutputCustomizer.java]: should we set an accessor  ?

**Review by benoitf — APPROVED** [review]

File: ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/console/DefaultOutputCustomizer.java (hunk 2 above)
Comment (vrubezhny) [reply ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/console/DefaultOutputCustomizer.java]: I've meant to make it to be package package available this time. Can't imagine a class that may be in need of calling this method other than these two `*OutputCustomizer`-classes at the moment.
If output customizers will be distributed among the different packages in future, we'll have to make it to be like public API. However at the moment, we have all these classes placed closely in one package and we don't have a mean that let adopters to add their own customizers - so no need to make it like public API.
IMHO

File: ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/console/CSharpOutputCustomizer.java (hunk 1 above)
Comment (vrubezhny) [reply ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/console/CSharpOutputCustomizer.java:27]: Next time is OK?
Or I should add it to all the output customizer like classes (as well as to those which was added only in fix for CHE-15)?

Comment (benoitf) [reply ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/console/CSharpOutputCustomizer.java:27]: I approved the PR so it's up to you

File: ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/console/DefaultOutputCustomizer.java (hunk 2 above)
Comment (benoitf) [reply ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/console/DefaultOutputCustomizer.java]: I was thinking private but it was more a thought. No change requested.

Comment (vrubezhny) [reply ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/console/DefaultOutputCustomizer.java]: No, it can't be private - it's used from two different classes in the same package.

Comment (benoitf) [reply ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/console/DefaultOutputCustomizer.java]: my feeling was that DefaultOutputCustomizer is not a default one, it's including Java or JavaScript.
So static code should be moved in a Empty/base or default class
But we should have Java(Script)OutputCustomizer and CSharpOutputCustomizer (they could both extend the same class)

**Review by slemeur — APPROVED** [review]
👍

**Comment by benoitf** [comment]
@vparfonov ?

File: ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/console/DefaultOutputCustomizer.java (hunk 2 above)
Comment (vrubezhny) [reply ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/console/DefaultOutputCustomizer.java]: @benoitf  I have the same feeling. `Default*` was like a first impression (and because java is most used language, imho) - so, with having two more customizers [at the moment] it doesn't look like a proper name for this kind of customizer. 

So, shell I turn DefaultOutputCustomizer into an abstract class (with few utility methods, like `openFileInEditorAndReveal(...)`, `selectRange(...)` and set of abstract methods of `OutputCustomizer` interface) and a class like JavaOutputCustomizer (with realization for Java/JavaScript stacktraces)? (before the applying of this PR I mean)

Comment (benoitf) [reply ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/console/DefaultOutputCustomizer.java]: @vrubezhny I would say that it may be clearer this way, yes

Comment (vrubezhny) [reply ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/console/DefaultOutputCustomizer.java]: @benoitf @slemeur I've pushed a fixup commit that separates DefaultOutputCustomizer into AbstractOutputCustomizer (with some commonly used utility methods) and JavaOutputCustomizer. All the existing customizers are adopted to this change.
The similar thing is made for JUnit tests: DefaultOutputCustomizerTest is separated into BaseOutputCustomizerTest (contains commonly used utility methods) and JavaOutputCustomizerTest. All the existing output customizer tests are adopted to this change as well.

**Comment by vrubezhny** [comment]
@benoitf @slemeur Please review with the latest changes.

**Comment by benoitf** [comment]
ci-build

**Review by benoitf — APPROVED** [review]

File: ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/console/DefaultOutputCustomizer.java (hunk 2 above)
Comment (benoitf) [reply ide/che-core-ide-app/src/main/java/org/eclipse/che/ide/console/DefaultOutputCustomizer.java]: @vrubezhny yes it's definitely better. Thanks.

**Review by vparfonov — APPROVED** [review]

**Comment by ghost** [comment]
@vparfonov @benoitf if we're ok with merging it, let's do it. Maybe a full QA cycle is required?
