### PR TITLE
Fix Java based devfile tests.

### LINKED ISSUE #16166: Test for error highlighting failing
### Describe the bug
Test for error highlighting is failing from time to time. The failure was seen in e.g. Java Maven test. 

Error in test log:
`TimeoutError: Waiting for element to be located By(xpath, //div[contains(@style, 'top:190px')]//div[contains(@class, 'squiggly-error')])` 

The page source code of a fallen element:
Screenshot from 2020-02-27 17-54-00

You can see that in a log the parent element for an error highlighting should have `top:190px`, which is according to the screenshot the line above the wanted one.

### PR DESCRIPTION
**Pull request by rhopp**
Fixes #16166 

plus few minor improvements

Signed-off-by: Radim Hopp <rhopp@redhat.com>

### What does this PR do?
This is mainly a workaround - When the lookup for error "squiggly-line" fails for the first time on TimeoutError, we just suppose it was because "Run|Debug" appeared and we just try this again.

### What issues does this PR fix or reference?
#16166

### CODE REVIEW

**Comment by rhopp** [comment]
crw-ci-test

**Review by Katka92 — APPROVED** [review]

**Comment by rhopp** [comment]
crw-ci-test

**Comment by rhopp** [comment]
crw-ci-test

**Comment by rhopp** [comment]
crw-ci-test

File: tests/e2e/utils/requestHandlers/tokens/CheMultiuserTokenHandler.ts [hunk 1]
```diff
@@ -37,4 +37,16 @@ export class CheMultiuserTokenHandler implements ITokenHandler {
         }
 
     }
+
+    /**
+     * Append `/` if it's not in the URL yet. Keycloak doesn't handle double `//` in URL well.
```
Comment (Ohrimenko1988) [inline tests/e2e/utils/requestHandlers/tokens/CheMultiuserTokenHandler.ts:42]: Could you please clarify what exactly this method does?
Because it is a bit understandable for me.
Or show an example.

Comment (rhopp) [reply tests/e2e/utils/requestHandlers/tokens/CheMultiuserTokenHandler.ts:42]: If `keycloakUrl` ends with `/` it does nothing.
If `keycloakUrl` does not end with `/`, it adds it.

This is because before these changes, when `TS_SELENIUM_BASE_URL` ended with `/`, resulting keycloakUrl (on line 23) was in format `<keycloakUrl>//auth/realms...` (notice the double `//` in the URL) and keycloak was not able to handle this correctly.
The changes in this file are to ensure that the resulting keycloak URL will not have the double forward slashes.

Comment (Ohrimenko1988) [reply tests/e2e/utils/requestHandlers/tokens/CheMultiuserTokenHandler.ts:42]: Ok, I see, thank you for responding.
Could it be also helpful for other environment variables which provide URL's ?

I don't push you to implement this for the current PR, I just suggest create an issue for that.

**Review by Ohrimenko1988 — APPROVED** [review]

File: tests/e2e/utils/requestHandlers/tokens/CheMultiuserTokenHandler.ts (hunk 1 above)
Comment (rhopp) [reply tests/e2e/utils/requestHandlers/tokens/CheMultiuserTokenHandler.ts:42]: I didn't see this problem with other URL's. I would create issue if I encounter this on some other place as well. Thanks ;-)

Comment (Ohrimenko1988) [reply tests/e2e/utils/requestHandlers/tokens/CheMultiuserTokenHandler.ts:42]: For example, if you provide the "TS_SELENIUM_BASE_URL" with the "/" at the end it will leads to the error in the "HappyPath" test which opens workspace by direct URL which includes also this variable value.
