### PR TITLE
CHE-2470: Fix usage of machine servers in environemnt configuration

### LINKED ISSUE #2470: Servers in machine config are not applied to runtime after workspace restart
The attribute **servers** in machine config in environment config is not applied to runtime, after workspace restart.

```
...
servers: {
 1024/tcp: {
   port: "1024",
   properties: { },
   protocol: "http"
}
...
```

**Reproduction Steps:**
1. Add ports in machine configuration
2. Restart workspace
3. Go to Machines perspective
4. 

**Expected behavior:**

The servers tab contains mentioned port.

**Observed behavior:**

The servers tab doesn't contain mentioned port.

### PR DESCRIPTION
**Pull request by garagatyi**
### What does this PR do?

Fixes exposing of servers in machine that were defined in environment configuration.
### What issues does this PR fix or reference?

Fixes #2470 
### Previous behavior

Servers were not exposed.
### New behavior

Servers are exposed.
### PR type
- [x] Minor change = no change to existing features or docs
- [ ] ~~Major change = changes existing features or docs~~
### Minor change checklist
- [ ] ~~New API required?~~
- [ ] ~~API updated~~
- [x] Tests provided / updated
- [ ] Tests passed

### CODE REVIEW

**Comment by garagatyi** [comment]
@skabashnyuk @evoevodin @sleshchenko @akorneta Please review

File: wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/environment/server/EnvironmentParser.java [hunk 1]
```diff
@@ -78,36 +85,79 @@ public CheServicesEnvironmentImpl parse(Environment environment) throws IllegalA
...
+                normalizeMachine(name, service, extendedMachine);
             }
         });
 
-        return composeEnvironment;
+        return cheServicesEnvironment;
+    }
+
+    private void normalizeMachine(String name, CheServiceImpl service, ExtendedMachine extendedMachine) {
+        if (extendedMachine.getAttributes() != null &&
```
Comment (sleshchenko) [inline wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/environment/server/EnvironmentParser.java]: As far I as know our POJO and DTO objects should return empty collections instead of null values

File: wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/environment/server/EnvironmentParser.java [hunk 2]
```diff
@@ -78,36 +85,79 @@ public CheServicesEnvironmentImpl parse(Environment environment) throws IllegalA
...
+            extendedMachine.getAttributes().containsKey("memoryLimitBytes")) {
+
+            try {
+                service.setMemLimit(Long.parseLong(extendedMachine.getAttributes().get("memoryLimitBytes")));
+            } catch (NumberFormatException e) {
+                throw new IllegalArgumentException(
+                        format("Value of attribute 'memoryLimitBytes' of machine '%s' is illegal", name));
+            }
+        }
+        if (service.getExpose() != null) {
```
Comment (sleshchenko) [inline wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/environment/server/EnvironmentParser.java]: the same to https://github.com/eclipse/che/pull/2599/files#r80632123
CheServiceImpl#getExpose returns new ArrayList<String>() instead of null https://github.com/eclipse/che/blob/master/wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/environment/server/model/CheServiceImpl.java#L285-290

**Comment by sleshchenko** [comment]
Looks like there is typo in your email (agaragatyi@codenvy.comqa) in committer and author information. Please fix it

**Comment by akorneta** [comment]
ok

File: wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/environment/server/EnvironmentParser.java [hunk 3]
```diff
@@ -78,36 +85,79 @@ public CheServicesEnvironmentImpl parse(Environment environment) throws IllegalA
...
+            service.setExpose(service.getExpose()
+                                     .stream()
+                                     .map(expose -> expose.contains("/") ?
```
Comment (voievodin) [inline wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/environment/server/EnvironmentParser.java]: i'd probably change it to 

``` java
service.getExpose()
       .stream()
       .filter(expose -> !expose.contains("/"))
       .map(expose -> expose + "/tcp")
       .collect(toList())
```

File: wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/environment/server/EnvironmentParser.java [hunk 4]
```diff
@@ -78,36 +85,79 @@ public CheServicesEnvironmentImpl parse(Environment environment) throws IllegalA
...
+                                                    expose :
+                                                    expose + "/tcp")
+                                     .collect(toList()));
+        }
+        if (extendedMachine.getServers() != null) {
+            extendedMachine.getServers().forEach((serverRef, serverConf) -> {
```
Comment (voievodin) [inline wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/environment/server/EnvironmentParser.java]: Why doesn't the native foreach work here?

File: wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/environment/server/EnvironmentParser.java [hunk 5]
```diff
@@ -78,36 +85,79 @@ public CheServicesEnvironmentImpl parse(Environment environment) throws IllegalA
...
+                String normalizedPort = serverConf.getPort().contains("/") ?
+                                        serverConf.getPort() :
+                                        serverConf.getPort() + "/tcp";
+
+                service.getExpose().add(normalizedPort);
+
+                service.getLabels().put(SERVER_CONF_LABEL_PREFIX +
```
Comment (voievodin) [inline wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/environment/server/EnvironmentParser.java]: You check all the object not to be nulls, should you check labels as well?

File: wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/environment/server/EnvironmentParser.java [hunk 6]
```diff
@@ -78,36 +85,79 @@ public CheServicesEnvironmentImpl parse(Environment environment) throws IllegalA
...
+                                        normalizedPort +
+                                        SERVER_CONF_LABEL_REF_SUFFIX,
+                                        serverRef);
+                if (serverConf.getProperties() != null && serverConf.getProperties().get("path") != null) {
+
+                    service.getLabels().put(SERVER_CONF_LABEL_PREFIX +
```
Comment (voievodin) [inline wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/environment/server/EnvironmentParser.java]: It looks like  `SERVER_CONF_LABEL_PREFIX + normalizedPort` deserves a separate variable as the concatenation will be repeated 3 times in a raw if properties and protocol exist

**Review by voievodin — CHANGES_REQUESTED** [review]

**Review by voievodin — APPROVED** [review]

**Review by akorneta — APPROVED** [review]
ok

File: wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/environment/server/EnvironmentParser.java (hunk 1 above)
Comment (garagatyi) [reply wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/environment/server/EnvironmentParser.java]: Yes, but this object may come from Everrest as a proxy object

File: wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/environment/server/EnvironmentParser.java (hunk 2 above)
Comment (garagatyi) [reply wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/environment/server/EnvironmentParser.java]: Yes, but this object may come from Everrest as a proxy object

File: wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/environment/server/EnvironmentParser.java (hunk 3 above)
Comment (garagatyi) [reply wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/environment/server/EnvironmentParser.java]: But what if some expose values already contains /tcp. Will they be removed?

Comment (voievodin) [reply wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/environment/server/EnvironmentParser.java]: Oh yes, sorry, i missed that you still need the other exposes

File: wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/environment/server/EnvironmentParser.java (hunk 4 above)
Comment (garagatyi) [reply wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/environment/server/EnvironmentParser.java]: Sorry, I didn't understand what you mean.

File: wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/environment/server/EnvironmentParser.java (hunk 5 above)
Comment (garagatyi) [reply wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/environment/server/EnvironmentParser.java]: labels are part of non-rest code, so it returns empty collections always and proxy doesn't affect it

File: wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/environment/server/EnvironmentParser.java (hunk 4 above)
Comment (garagatyi) [reply wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/environment/server/EnvironmentParser.java]: I think it is OK to leave that code with this construct instead of common loop over entries

File: wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/environment/server/EnvironmentParser.java (hunk 6 above)
Comment (garagatyi) [reply wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/environment/server/EnvironmentParser.java]: ok

File: wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/environment/server/EnvironmentParser.java (hunk 1 above)
Comment (garagatyi) [reply wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/environment/server/EnvironmentParser.java]: Actually this class uses model interface, so it is not guarantied that DTO or default impl is used

File: wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/environment/server/EnvironmentParser.java (hunk 2 above)
Comment (sleshchenko) [reply wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/environment/server/EnvironmentParser.java]: As far as I understand you create this instance here https://github.com/eclipse/che/pull/2599/files#diff-0adf8dd72b68fcf12958c9f8602151e0R209

Comment (garagatyi) [reply wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/environment/server/EnvironmentParser.java]: changed
