### PR TITLE
prevent workspace restarting if user intentionally stopped it

### LINKED ISSUE #14567: Workspace is continuously restarted after start interruption
### Describe the bug
This is nasty bug when a user cannot interrupt start of a workspace. The only way to stop it just wait until it fully started and only then stop it.

### Che version
nightly

### Steps to reproduce

1. Start a workspace
2. In a few second, while it is starting, click on `Stop` button
3. Workspace start willbe interrupted and right after it, Che will try to start the same workspace again.

### Expected behavior
Workspace start should be interrupted

### Runtime
Minikube, Minishift
Che multiuser

### Additional context
We had [the same problem before](https://github.com/eclipse/che/issues/11077) but it was fixed and now appeared again.

### PR DESCRIPTION
**Pull request by akurinnoy**
Signed-off-by: Oleksii Kurinnyi <okurinny@redhat.com>

### What does this PR do?

Fix bug when user cannot interrupt a workspace start.

### What issues does this PR fix or reference?

fixes https://github.com/eclipse/che/issues/14567

### CODE REVIEW

**Review by mmorhun — APPROVED** [review]

**Review by olexii4 — APPROVED** [review]

**Review by AndrienkoAleksandr — APPROVED** [review]

**Review by evidolob — APPROVED** [review]

File: workspace-loader/src/workspace-loader.ts [hunk 1]
```diff
@@ -26,6 +26,10 @@ export class WorkspaceLoader {
     private workspace: che.workspace.Workspace;
     private runtimeIsAccessible: Deferred<void>;
 
+    // `false` if workspace has been stopped intentionally
+    // and workspace-loader should not restart it
+    private doRestart: boolean = true;
```
Comment (vitaliy-guliy) [inline workspace-loader/src/workspace-loader.ts]: I'm confused. Restart means the sequence of actions: stop and then start. Is this variable indeed means that?

Comment (akurinnoy) [reply workspace-loader/src/workspace-loader.ts]: It's not the best name, indeed. I suppose that `allowRestart` makes more sense, doesn't it?

Comment (vitaliy-guliy) [reply workspace-loader/src/workspace-loader.ts]: Let it be `allowRestart`

**Review by vitaliy-guliy — APPROVED** [review]

**Comment by dmytro-ndp** [comment]
ci-build

**Comment by dmytro-ndp** [comment]
ci-test

**Comment by dmytro-ndp** [comment]
crw-ci-test

**Comment by akurinnoy** [comment]
ci-build

**Comment by akurinnoy** [comment]
ci-test

**Comment by dmytro-ndp** [comment]
@akurinnoy: there is expected regression in [Java selenium tests](https://github.com/eclipse/che/pull/14728#issuecomment-539577566). It was fixed yesterday https://github.com/eclipse/che/commit/720aab005106015646b2d13da6428656c0cda178.
