### PR TITLE
CHE-6317: rework script to deploy Che to OS

### LINKED ISSUE #6317: Che fails to start a workspace on OpenShift in spi branch
Related to SPI branch only.
After last changes, OpenShift infrastructure implementation workspaces don't start. The reason is that URL of websocket endpoint provided by Che is wrong. It should be `<che-host-on-openshift>/wsmaster/websocket` but now it is `<che-host-on-openshift>:8080/wsmaster/websocket`. 
Because of that bootstrapper of installers fails to connect to push statuses and logs on installers.

**Reproduction Steps:**
1. Start WS on OpenShift.

It fails to start.

**OS and version:**    

**Diagnostics:**

### PR DESCRIPTION
**Pull request by garagatyi**
### What does this PR do?
Rework script that deploys Che to OpenShift in accordance with changes in the SPI branch.

### What issues does this PR fix or reference?
Fixes #6317 

#### Changelog
Rework script that deploys Che to OpenShift in accordance with changes in the SPI branch.

### CODE REVIEW

**Review by l0rd — APPROVED** [review]

File: dockerfiles/cli/scripts/openshift/deploy_che.sh [hunk 1]
```diff
@@ -254,7 +254,10 @@ CHE_IMAGE_SANITIZED=$(echo "${CHE_IMAGE}" | sed 's/\//\\\//g')
 echo
 if [ "${OPENSHIFT_FLAVOR}" == "minishift" ]; then
   echo "[CHE] Deploying Che on minishift (image ${CHE_IMAGE})"
-  curl -sSL http://central.maven.org/maven2/io/fabric8/tenant/apps/che/"${OSIO_VERSION}"/che-"${OSIO_VERSION}"-openshift.yml | \
+  DEFAULT_CHE_DEPLOYMENT_URL=https://gist.githubusercontent.com/garagatyi/20e63a0d3c7b1a2a82a262eb2f8bcde1/raw/2716217b5dfa67c04283883b1df85fae364aadd4/che-spi-openshift.yml
```
Comment (benoitf) [inline dockerfiles/cli/scripts/openshift/deploy_che.sh]: could we use another stuff than a gist ?
updating the gist will result in a new URL so maybe we need to store the file locally ?

Comment (garagatyi) [reply dockerfiles/cli/scripts/openshift/deploy_che.sh]: @l0rd WDYT if we put configuration of openshift objects into repo?

Comment (l0rd) [reply dockerfiles/cli/scripts/openshift/deploy_che.sh]: @garagatyi +1

Comment (garagatyi) [reply dockerfiles/cli/scripts/openshift/deploy_che.sh]: done

Comment (benoitf) [reply dockerfiles/cli/scripts/openshift/deploy_che.sh]: @garagatyi there are warnings on https://www.shellcheck.net/

Comment (garagatyi) [reply dockerfiles/cli/scripts/openshift/deploy_che.sh]: I fixed only one.
The one about `cat` is not so obvious that it would look better.
Others are false positives.

File: dockerfiles/cli/scripts/openshift/deploy_che.sh [hunk 2]
```diff
@@ -266,8 +269,14 @@ if [ "${OPENSHIFT_FLAVOR}" == "minishift" ]; then
     sed "s/    che.predefined.stacks.reload_on_start: \"true\"/    che.predefined.stacks.reload_on_start: \"false\"/" | \
     sed "s|    keycloak-oso-endpoint:.*|    keycloak-oso-endpoint: ${KEYCLOAK_OSO_ENDPOINT}|" | \
     sed "s|    keycloak-github-endpoint:.*|    keycloak-github-endpoint: ${KEYCLOAK_GITHUB_ENDPOINT}|" | \
+    sed "s|    CHE_INFRA_OPENSHIFT_MASTER__URL:.*|    CHE_INFRA_OPENSHIFT_MASTER__URL: ${DEFAULT_OPENSHIFT_ENDPOINT}|" | \
+    sed "s|    CHE_INFRA_OPENSHIFT_BOOTSTRAPPER_BINARY__URL:.*|    CHE_INFRA_OPENSHIFT_BOOTSTRAPPER_BINARY__URL: http://che-${DEFAULT_OPENSHIFT_NAMESPACE_URL}/agent-binaries/linux_amd64/bootstrapper/bootstrapper|" | \
+    sed "s|    CHE_WEBSOCKET_ENDPOINT:.*|    CHE_WEBSOCKET_ENDPOINT: ws://che-${DEFAULT_OPENSHIFT_NAMESPACE_URL}/wsmaster/websocket|" | \
+    sed "s|    CHE_HOST: "'${DEFAULT_OPENSHIFT_NAMESPACE_URL}'"|    CHE_HOST: che-${DEFAULT_OPENSHIFT_NAMESPACE_URL}|" | \
```
Comment (benoitf) [inline dockerfiles/cli/scripts/openshift/deploy_che.sh]:
```
sed "s|    CHE_HOST: \${DEFAULT_OPENSHIFT_NAMESPACE_URL}|    CHE_HOST: che-${DEFAULT_OPENSHIFT_NAMESPACE_URL}|"

```
avoid false positive and remove a lot of quotes

Comment (garagatyi) [reply dockerfiles/cli/scripts/openshift/deploy_che.sh]: ur right. added to the PR.

**Review by benoitf — APPROVED** [review]

**Review by riuvshin — APPROVED** [review]
