### PR TITLE
fix wait CHE pod in deploy script

### LINKED ISSUE #9184: Che deployment script on OCP doesn't wait until progressing status became true or false
### Description
Execution of selenium tests on [pull request build CI job](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/80/consoleText) shown the problem with deploying Che on OCP: **deploy_ocp.sh** didn't wait until _Progressing.status_ changes from **Unknown** to **True** or **False** and aborted execution just after _Available.status_ had became **True**:
```
[CHE] Deployment is in progress...(Available.status="False", Progressing.status="Unknown", Timeout in 299s)
[CHE] Deployment is in progress...(Available.status="False", Progressing.status="Unknown", Timeout in 294s)
[CHE] Deployment is in progress...(Available.status="False", Progressing.status="Unknown", Timeout in 288s)
[CHE] Deployment is in progress...(Available.status="False", Progressing.status="Unknown", Timeout in 282s)
[CHE] Deployment is in progress...(Available.status="True", Progressing.status="Unknown", Timeout in 277s)
[CHE] [ERROR] Deployment timeout. Aborting.
```

It was also reproduced locally:
```
[CHE] Inferring $CHE_API_ENDPOINT...done (http://che-eclipse-che.172.19.20.32.nip.io/api)
[CHE] Deployment is in progress...(Available.status="False", Progressing.status="Unknown", Timeout in 299s)
[CHE] Deployment is in progress...(Available.status="False", Progressing.status="Unknown", Timeout in 294s)
[CHE] Deployment is in progress...(Available.status="False", Progressing.status="Unknown", Timeout in 288s)
[CHE] Deployment is in progress...(Available.status="False", Progressing.status="Unknown", Timeout in 282s)
[CHE] Deployment is in progress...(Available.status="False", Progressing.status="Unknown", Timeout in 277s)
[CHE] Deployment is in progress...(Available.status="False", Progressing.status="Unknown", Timeout in 271s)
[CHE] Deployment is in progress...(Available.status="False", Progressing.status="Unknown", Timeout in 265s)
[CHE] Deployment is in progress...(Available.status="False", Progressing.status="Unknown", Timeout in 259s)
[CHE] Deployment is in progress...(Available.status="False", Progressing.status="Unknown", Timeout in 254s)
[CHE] Deployment is in progress...(Available.status="True", Progressing.status="Unknown", Timeout in 248s)
[CHE] [ERROR] Deployment timeout. Aborting.
```

**OS and version:**    

**Diagnostics:**

### PR DESCRIPTION
**Pull request by riuvshin**
both `available` and `progressing` should be "True" to treat deployment as successful

fixes: https://github.com/eclipse/che/issues/9184

### CODE REVIEW

**Review by ghost — APPROVED** [review]

**Review by sleshchenko — APPROVED** [review]

File: deploy/openshift/deploy_che.sh [hunk 1]
```diff
@@ -65,7 +65,7 @@ wait_until_che_is_available() {
     DEPLOYMENT_TIMEOUT_SEC=300
     POLLING_INTERVAL_SEC=5
     end=$((SECONDS+DEPLOYMENT_TIMEOUT_SEC))
-    while [ "${available}" != "\"True\"" ] && [ ${SECONDS} -lt ${end} ]; do
+    while [[ "${available}" != "\"True\"" || "${progressing}" != "\"True\"" ]] && [ ${SECONDS} -lt ${end} ]; do
```
Comment (dmytro-ndp) [inline deploy/openshift/deploy_che.sh:68]: It would look simpler if we replace 
`[[ "${available}" != "\"True\"" || "${progressing}" != "\"True\"" ]]`
on
`! [[ "${available}" == "\"True\"" && "${progressing}" == "\"True\"" ]]`

Comment (dmytro-ndp) [reply deploy/openshift/deploy_che.sh:68]: Or even simpler 
`! [ "${available}" == "\"True\"" ] && ! [ "${progressing}" == "\"True\"" ] && [ ${SECONDS} -lt ${end} ]`

Comment (sleshchenko) [reply deploy/openshift/deploy_che.sh:68]: Personally, I think it wouldn't. For me easier to understand local negation but not complex one.

Comment (riuvshin) [reply deploy/openshift/deploy_che.sh:68]: @dmytro-ndp you can propose another PR with improvement but please consider all places with such codestyle.

Comment (garagatyi) [reply deploy/openshift/deploy_che.sh:68]: From my experience, a negation of a set of expressions is harder for understanding and fast reading of the code than several negations of simple and small expressions. So I opt to leave it as is

Comment (sleshchenko) [reply deploy/openshift/deploy_che.sh:68]: > Or even simpler
> ! [ "${available}" == "\"True\"" ] && ! [ "${progressing}" == "\"True\"" ] && [ ${SECONDS} -lt ${end} ]

I agree that it is simpler. But I'm afraid that it works differently from original if statement
I mean that you can't transform `(!A || !B) & C` to `!A & !B & C`

Comment (dmytro-ndp) [reply deploy/openshift/deploy_che.sh]: @garagatyi: 
> several negations of simple and small expressions
that is what I has proposed as second variant: 
`! [ "${available}" == "\"True\"" ] && ! [ "${progressing}" == "\"True\"" ] && [ ${SECONDS} -lt ${end} ]`

**Review by garagatyi — APPROVED** [review]

File: deploy/openshift/deploy_che.sh (hunk 1 above)
Comment (dmytro-ndp) [reply deploy/openshift/deploy_che.sh:68]: @sleshchenko: my fault. You are right.
