### PR TITLE
LuceneSearcher redesign and fix memory leak

### LINKED ISSUE #8111: Memory leak during removal of document from Lucene index
### Description
Since we are not doing ```indexWriter.commit``` all deletition are persisted in memory.

### Reproduction Steps
1. Index large directory tree. Like ```node_modules```
2. Delete folder.
3. Notes that memory consumption of ```ws-agent``` increases significantly.

### PR DESCRIPTION
**Pull request by skabashnyuk**
### What does this PR do?
LuceneSearcher redesign and fix memory leak
- org.eclipse.che.api.search.server.Searcher reworked exceptions. Instead of transport exceptions, it will throw search specific exceptions. 
- OffsetData moved to separate class, outside from LuceneSearcher.
- QueryExpression and OffsetData now on the same level as Searcher interface
- Used dedicated one-time used demon thread for initial indexing instead of thread pool
- Added CountDownLatch to test if initial indexing complete.
- Removed dependency on org.eclipse.jface.text in offset calculation
- Used Files.walkFileTree to simplify ```add``` directory method
- added ```printStatistic``` method to put some statistics in log.debug output
- optimized ```delete``` method to the fact that is called after folder or file removal
- Called ```indexWriter.commit``` after adding, update, removal of  file or folder 
- Added implementation agnostic test for org.eclipse.che.api.search.server.Searcher
- Added specific to LuceneSearche test
 

### What issues does this PR fix or reference?
Fixes https://github.com/eclipse/che/issues/8111

#### Release Notes
LuceneSearcher redesign and fix memory leak

#### Docs PR
n/a

### CODE REVIEW

**Comment by skabashnyuk** [comment]
ci-test

**Review by dkulieshov — APPROVED** [review]

**Comment by skabashnyuk** [comment]
ci-test

**Comment by skabashnyuk** [comment]
ci-test

File: wsagent/che-core-api-project/src/main/java/org/eclipse/che/api/project/server/impl/ProjectServiceApi.java [hunk 1]
```diff
@@ -680,7 +692,7 @@ public ProjectSearchResponseDto search(ProjectSearchRequestDto request) {
 
     try {
       return search(path, name, text, maxItems, skipCount);
-    } catch (ServerException | ConflictException | NotFoundException | ForbiddenException e) {
+    } catch (ServerException | NotFoundException | BadRequestException e) {
```
Comment (garagatyi) [inline wsagent/che-core-api-project/src/main/java/org/eclipse/che/api/project/server/impl/ProjectServiceApi.java:695]: Not sure it makes sense to throw these exceptions in other code to lose the information about exception type here.

**Review by garagatyi — APPROVED** [review]

**Comment by skabashnyuk** [comment]
ci-test

**Comment by skabashnyuk** [comment]
ci-test

**Comment by skabashnyuk** [comment]
ci-test

**Comment by skabashnyuk** [comment]
ci-test

**Comment by skabashnyuk** [comment]
ci-test

**Comment by skabashnyuk** [comment]
ci-test

**Comment by skabashnyuk** [comment]
ci-test

**Comment by skabashnyuk** [comment]
ci-test

**Review by vparfonov — APPROVED** [review]

**Comment by mkuznyetsov** [comment]
ci-test
