### PR TITLE
Distinct interrupted from failed to start workspace metric

### LINKED ISSUE #18158: If a worspace failed to start due to the fact that user stopped it explicitly we should not count it as a failure from the metrics perspective
### Che version
- 7.20.0

### Steps to reproduce

- Start a workspace 
- While workspace is in the "STARTING" state go to UD and stop it explicitly
- See the error message - 'Failed
Runtime start for identity 'workspace: xxx, environment: default, ownerId id' is interrupted' 
- in the logs there will be smth. like

`{"@timestamp":"2020-10-21T13:24:29.677+00:00","@version":1,"message":"Failed to start Kubernetes runtime of workspace workspaceuuuxkjuse6hvvme8.","logger_name":"org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesInternalRuntime","thread_name":"WorkspaceSharedPool-28","level":"WARN","level_value":30000,"stack_trace":"org.eclipse.che.api.workspace.server.spi.RuntimeStartInterruptedException: Runtime start for identity 'workspace: xxx, environment: default, ownerId: id' is interrupted}`

- ERROR: Prometheus failure count has been incremented

### Expected behavior

-  Prometheus failure count should not be incremented since the failure is user driven and expected

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Eclipse Che Logs

`{"@timestamp":"2020-10-21T13:24:29.677+00:00","@version":1,"message":"Failed to start Kubernetes runtime of workspace workspaceuuuxkjuse6hvvme8.","logger_name":"org.eclipse.che.workspace.infrastructure.kubernetes.KubernetesInternalRuntime","thread_name":"WorkspaceSharedPool-28","level":"WARN","level_value":30000,"stack_trace":"org.eclipse.che.api.workspace.server.spi.RuntimeStartInterruptedException: Runtime start for identity 'workspace: xxx, environment: default, ownerId: id' is interrupted}`

### PR DESCRIPTION
**Pull request by skabashnyuk**
### What does this PR do?
Distinct interrupted from failed to start workspace metric

### Screenshot/screencast of this PR
Знімок екрана 2020-11-02 о 14 04 26

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/18158

### How to test this PR?
1. Deploy `quay.io/skabashn/che-server:che18158`
2.  Run che with enabled metrics.
3. Start and interrupt workspace startup. 
4. Check metrics. `che_workspace_failure_total{area="workspace",while="STARTING",}` - should remain the same. 
`che_workspace_start_interrupt_total` should be increased.
### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [x] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [x] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [ ] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

**Comment by skabashnyuk** [comment]
[crw-ci-test]

File: wsmaster/che-core-api-workspace-shared/src/main/java/org/eclipse/che/api/workspace/shared/dto/event/WorkspaceStatusEvent.java [hunk 1]
```diff
@@ -64,4 +64,9 @@
   Map<String, String> getOptions();
 
   WorkspaceStatusEvent withOptions(Map<String, String> options);
+
+  /** @return whether workspace startup was interrupted by user */
+  boolean isStartupInterrupted();
```
Comment (metlos) [inline wsmaster/che-core-api-workspace-shared/src/main/java/org/eclipse/che/api/workspace/shared/dto/event/WorkspaceStatusEvent.java]: What about calling this `isInitiatedByUser()`? Because that's what I think we really want to distinguish, isn't it? User-initiated state changes from "environmental" changes in the state.

This way, we could for example also distinguish a user initiated workspace stop from a forced stop due to inactivity (or, God forbid, a user-initiated workspace start from some kind of automated workspace start) without changing the DTO model.

Comment (skabashnyuk) [reply wsmaster/che-core-api-workspace-shared/src/main/java/org/eclipse/che/api/workspace/shared/dto/event/WorkspaceStatusEvent.java]: interesting idea. I'll take a look.

File: wsmaster/che-core-api-metrics/src/main/java/org/eclipse/che/api/metrics/WorkspaceFailureMeterBinder.java [hunk 2]
```diff
@@ -50,10 +51,11 @@ public void bindTo(MeterRegistry registry) {
     // only subscribe to the event once we have the counters ready
     eventService.subscribe(
         event -> {
-          if (event.getError() == null || event.getStatus() != WorkspaceStatus.STOPPED) {
+          if (event.getError() == null
```
Comment (ibuziuk) [inline wsmaster/che-core-api-metrics/src/main/java/org/eclipse/che/api/metrics/WorkspaceFailureMeterBinder.java:54]: just to confirm: `event.getError()` returns non `null` value if a user explicitly stops workspace during startup?

Comment (skabashnyuk) [reply wsmaster/che-core-api-metrics/src/main/java/org/eclipse/che/api/metrics/WorkspaceFailureMeterBinder.java:54]: In that case, error would have a value `"Runtime start for identity 'workspace: %s, environment: %s, ownerId: %s' is interrupted"`

Comment (skabashnyuk) [reply wsmaster/che-core-api-metrics/src/main/java/org/eclipse/che/api/metrics/WorkspaceFailureMeterBinder.java:54]: and `event.isInitiatedByUser=true`

**Review by ibuziuk — APPROVED** [review]

**Review by mshaposhnik — APPROVED** [review]

File: wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceRuntimes.java [hunk 3]
```diff
@@ -993,7 +1005,13 @@ public void run() {
...
           LOG.error(e.getLocalizedMessage(), e);
         }
-        publishWorkspaceStatusEvent(workspaceId, STOPPED, STARTING, e.getMessage());
+        publishWorkspaceStatusEvent(
+            workspaceId,
+            STOPPED,
+            STARTING,
+            e.getMessage(),
+            isWorkspaceStartInterrupted,
+            Collections.emptyMap());
```
Comment (sparkoo) [inline wsmaster/che-core-api-workspace/src/main/java/org/eclipse/che/api/workspace/server/WorkspaceRuntimes.java]: I think we don't need to pass `emptyMap()` explicitly as we have overloaded method that is doing that for us

**Review by sparkoo — APPROVED** [review]

**Review by metlos — APPROVED** [review]
