### PR TITLE
Set kubernetes namespace to null on workspace recipe parsing

### LINKED ISSUE #12626: Unable to start a workspace if k8s/OS object are created in a different from Che namespace
### Description
Unable to start a workspace if k8s/OS object are created in a different from Che namespace.

It happens because K8s API responds with an error that unable to create a resource in namespace workspace specific namespace because `che` namespace is predefined in object meta.

screenshot from 2019-02-07 13-33-20

I guess it is related with https://github.com/eclipse/che/pull/12583 because debugging shows that it is a line which set namespace che for recipe objects
https://github.com/eclipse/che/blob/26ce0947d9b00de16c55097e0c8fa264e7f6b509/infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/environment/KubernetesEnvironmentFactory.java#L103

screenshot from 2019-02-07 13-34-22

### Reproduction Steps
1. Deploy Che with `CHE_INFRA_KUBERNETES_NAMESPACE=""` for k8s infra or `CHE_INFRA_OPENSHIFT_PROJECT=""` for OS infra.
2. Try to start workspace from Che 7 stack.

**OS and version:**    
Che 6.18.0-SNAPSHOT. I guess 6.17.0 has the same issue.

### PR DESCRIPTION
**Pull request by garagatyi**
### What does this PR do?
Set kubernetes namespace to null on workspace recipe parsing.
Needed because current parsing sets Che master namespace and objects need to be created in another namespace in some cases.  
Thanks, @sleshchenko for the solution idea.  
Checked on minikube.

### What issues does this PR fix or reference?
Fixes https://github.com/eclipse/che/issues/12626

### CODE REVIEW

File: infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/environment/KubernetesEnvironmentFactory.java [hunk 1]
```diff
@@ -124,6 +124,8 @@ protected KubernetesEnvironment doCreate(
       checkNotNull(object.getMetadata(), "%s metadata must not be null", object.getKind());
       checkNotNull(object.getMetadata().getName(), "%s name must not be null", object.getKind());
 
+      object.getMetadata().setNamespace(null);
```
Comment (sleshchenko) [inline infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/environment/KubernetesEnvironmentFactory.java:128]: Please add a few words that it is needed because it is set to Che Server one by K8s API during list loading

**Review by sleshchenko — APPROVED** [review]
LGTM
Please consider adding comment why it is needed in both factories

**Review by ibuziuk — APPROVED** [review]

**Comment by garagatyi** [comment]
ci-test

File: infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/environment/KubernetesEnvironmentFactory.java (hunk 1 above)
Comment (garagatyi) [reply infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/environment/KubernetesEnvironmentFactory.java:128]: ok

**Review by amisevsk — APPROVED** [review]
I love a simple fix.
