### PR TITLE
CODENVY-593: fix workspace stopping

### LINKED ISSUE #593: Workspace is not deleted after finishing selenium test
We need to delete workspaces after finishing the selenium tests by API methods.

**Reproduction Steps:**
Run a selenium test in the 'qa' project (e.g. 'DialogAboutTest')

**Expected behavior:**
the workspace should be deleted after finishing test.

**Observed behavior:**
the workspace is not deleted.

**_Codenvy version:**_\* 4.7.0
**OS and version:** Ubuntu 14.04 

**Additional information:**
See the attachment:
log_error

### PR DESCRIPTION
**Pull request by garagatyi**
### What does this PR do?
Fixes bug in workspace stopping process. 

### What issues does this PR fix or reference?
Fixes codenvy/codenvy#593

### Previous behavior
After successful stop of workspace immediate removal fails because workspace is not fully stopped.

### New behavior
After stop of a workspace there is possibility to remove it immediately.

### CODE REVIEW

**Comment by garagatyi** [comment]
@evoevodin @skabashnyuk Please review

**Review by voievodin — APPROVED** [review]

File: wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/WorkspaceRuntimeIntegrationTest.java [hunk 1]
```diff
@@ -0,0 +1,194 @@
+package org.eclipse.che.api.workspace.server;
```
Comment (sleshchenko) [inline wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/WorkspaceRuntimeIntegrationTest.java:11]: Don't forget to add license

Comment (garagatyi) [reply wsmaster/che-core-api-workspace/src/test/java/org/eclipse/che/api/workspace/server/WorkspaceRuntimeIntegrationTest.java:11]: Nice catch! Thanks!

**Review by skabashnyuk — APPROVED** [review]

**Review by skabashnyuk — APPROVED** [review]
