### PR TITLE
Fix memory request jwt

### LINKED ISSUE #11547: Error to create jwtproxy sidecar on OSIO
### Description

Looks like the sidecar `resources.requests` is > to memory limit. When starting a Che 7 preview workspace on che.openshift.io I have the following error in the OpenShift events:

```
Error creating: Pod "workspaceataiwq6bp2cs9gsw.che-jwtproxy-864465cb55-k9rwr" is invalid: spec.containers[0].resources.requests: Invalid value: "150Mi": must be less than or equal to memory limit
```

### Reproduction Steps

- Add a Che 7 stack on osio (using this [raw config](https://gist.github.com/l0rd/2ff9391d9cabbc861d9e7e9102efcaf3))
- Start a workspace based on that stack
- Look at the events (`oc get events -w`)

### PR DESCRIPTION
**Pull request by garagatyi**
### What does this PR do?
**What:**
Set Memory request for JWT sidecar.
Ensure that all containers have a memory request is set and not
bigger than the memory limit.
**Why:**
When k8s/OS has a significant value of RAM request as default and Che doesn't set memory request and machine/sidecar RAM limit is lower we get an error from k8s/OS API about invalidness of pod spec since  RAM limit is lower than RAM request.

### What issues does this PR fix or reference?
Fixes https://github.com/eclipse/che/issues/11547

### CODE REVIEW

**Comment by garagatyi** [comment]
ci-test

**Review by skabashnyuk — APPROVED** [review]

File: infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/secure/jwtproxy/JwtProxyProvisioner.java [hunk 1]
```diff
@@ -114,13 +115,18 @@ public JwtProxyProvisioner(
...
 
     this.jwtProxyImage = jwtProxyImage;
-    this.memoryLimitBytes =
-        Size.parseSizeToMegabytes(memoryLimitBytes) * MEGABYTES_TO_BYTES_DEVIDER;
 
     this.proxyConfigBuilder = jwtProxyConfigBuilderFactory.create(identity.getWorkspaceId());
     this.identity = identity;
     this.serviceName = generate(SERVER_PREFIX, SERVER_UNIQUE_PART_SIZE) + "-jwtproxy";
     this.availablePort = FIRST_AVAILABLE_PORT;
+    long memoryLimitLong = Size.parseSizeToMegabytes(memoryLimitBytes) * MEGABYTES_TO_BYTES_DEVIDER;
```
Comment (mshaposhnik) [inline infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/secure/jwtproxy/JwtProxyProvisioner.java]: Call it ..._DIVIDER please :)

**Review by mshaposhnik — APPROVED** [review]

File: infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/secure/jwtproxy/JwtProxyProvisioner.java (hunk 1 above)
Comment (garagatyi) [reply infrastructures/kubernetes/src/main/java/org/eclipse/che/workspace/infrastructure/kubernetes/server/secure/jwtproxy/JwtProxyProvisioner.java]: Fixed

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/944/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/944//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11556
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Review by sleshchenko — APPROVED** [review]
LGTM

**Comment by garagatyi** [comment]
ci-test

**Comment by riuvshin** [comment]
Results of automated E2E tests of Eclipse Che Multiuser on OCP:
[Build details](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/945/)
[Test report](https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/945//Selenium_20tests_20report/)
docker image: eclipseche/che-server:11556
https://github.com/orgs/eclipse/teams/eclipse-che-qa please check this report.

**Comment by garagatyi** [comment]
@eclipse/eclipse-che-qa please, review the test report

**Comment by SkorikSergey** [comment]
Selenium tests execution on Eclipse Che Multiuser on OCP (https://ci.codenvycorp.com/job/che-pullrequests-test-ocp/945/) doesn't show any regression against this Pull Request.
