### PR TITLE
Validation of Bitbucket personal access token before usage

### LINKED ISSUE #19273: The default devfile is resolved from private bitbucket repo after access token is revoked
### Describe the bug
The default devfile is resolved from private bitbucket repo after access token is revoked.

### Che version

 - [ ] latest
 - [x] nightly
 - [ ] other: please specify

### Steps to reproduce
0. Prereq: Che with bitbucket oauth configured.
1. Open a factory which points to private bitbucket repo.
2. Authentication in the bitbucket after redirect.
3. Check that the right devfile is used for workspace creation.
my case:
```yaml
apiVersion: 1.0.0
metadata:
  generateName: wksp-
```
4. Go to bitbucket and revoke access to the generated token.
5. Retry accept the same factory.
Check that workspace is created but instead of resolved devfile, the default generated is used, like:
```yaml
apiVersion: 1.0.0
metadata:
  name: test-repo7hbgl
projects:
  - name: test-repo
    source:
      location: 'https://bitbucket-bitbucket.apps.cluster-460f.460f.sandbox1282.opentlc.com/scm/test/test-repo.git'
      type: git

```

### Expected behavior
User is ask to re-authenticate since Che owned token is already revoked.

### Runtime
   - [ ] kubernetes (include output of `kubectl version`)
   - [ ] Openshift (include output of `oc version`)
   - [ ] minikube (include output of `minikube version` and `kubectl version`)
   - [ ] minishift (include output of `minishift version` and `oc version`)
   - [ ] docker-desktop + K8S (include output of `docker version` and `kubectl version`)
   - [ ] other: (please specify)

### Screenshots

<details>
<summary>Screenshots</summary>

Screenshot_20210311_114036
Screenshot_20210311_114045
Screenshot_20210311_114055
Screenshot_20210311_114103

</details>

### Installation method
   - [ ] chectl
     * provide a full command that was used to deploy Eclipse Che (including the output)
     * provide an output of `chectl version` command
   - [ ] OperatorHub
   - [ ] I don't know

### Environment
   - [ ] my computer
       - [ ] Windows
       - [ ] Linux
       - [ ] macOS
   - [ ] Cloud
       - [ ] Amazon
       - [ ] Azure
       - [ ] GCE
       - [ ] other (please specify)
   - [ ] other: please specify

### Additional context
Bitbucket epic - https://github.com/eclipse/che/issues/18385

### PR DESCRIPTION
**Pull request by skabashnyuk**
### What does this PR do?
Validation of Bitbucket personal access token before usage

### What issues does this PR fix or reference?
Fixes https://github.com/eclipse/che/issues/19273

### How to test this PR?
 - deploy che-server image `quay.io/skabashn/che-server:che19273`
 - Create bitbucket factory like `https://che-eclipse-che.apps.cluster-6baf.6baf.sandbox449.opentlc.com/f?url=https://bitbucket-bitbucket.apps.cluster-6baf.6baf.sandbox449.opentlc.com/scm/che/che-server.git`
 - Authorise Che to create personal access token on BItbucket
 - Stop workspace
 - Go to the Bitbucket account page and disable existed che's personal access token
 - Try the factory one more time.

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [x] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [The repository devfile is up to date and works](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections `What issues does this PR fix or reference` and `How to test this PR` completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [x] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

### CODE REVIEW

File: infrastructures/infrastructure-factory/src/main/java/org/eclipse/che/api/factory/server/scm/kubernetes/KubernetesPersonalAccessTokenManager.java [hunk 1]
```diff
@@ -144,19 +150,29 @@ public PersonalAccessToken fetchAndSave(Subject cheUser, String scmServerUrl)
           Map<String, String> annotations = secret.getMetadata().getAnnotations();
           if (annotations.get(ANNOTATION_CHE_USERID).equals(cheUser.getUserId())
               && annotations.get(ANNOTATION_SCM_URL).equals(scmServerUrl)) {
-            return Optional.of(
+            LOG.info("Secret found {}", secret);
```
Comment (mshaposhnik) [inline infrastructures/infrastructure-factory/src/main/java/org/eclipse/che/api/factory/server/scm/kubernetes/KubernetesPersonalAccessTokenManager.java]: maybe LOG.debug ?

**Comment by mshaposhnik** [comment]
in general LGTM

**Comment by artaleks9** [comment]
Please, update to master branch

**Review by mshaposhnik — APPROVED** [review]

File: wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/scm/PersonalAccessTokenFetcher.java [hunk 2]
```diff
@@ -30,4 +31,19 @@
    */
   PersonalAccessToken fetchPersonalAccessToken(Subject cheUser, String scmServerUrl)
       throws ScmUnauthorizedException, ScmCommunicationException;
+
+  /**
+   * Checks whether the provided personal access token is valid and has expected scope of
+   * permissions.
+   *
+   * @param personalAccessToken - personal access token to check.
+   * @return - empty optional if @{@link PersonalAccessTokenFetcher} is not able to confirm or deny
```
Comment (mshaposhnik) [inline wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/scm/PersonalAccessTokenFetcher.java]: you do not need extra `@` before {@link}

File: wsmaster/che-core-api-factory-bitbucket-server/src/main/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketServerPersonalAccessTokenFetcher.java [hunk 3]
```diff
@@ -97,4 +102,25 @@ public PersonalAccessToken fetchPersonalAccessToken(Subject cheUser, String scmS
...
+          "not a  valid url {} for current fetcher ", personalAccessToken.getScmProviderUrl());
+      return Optional.empty();
+    }
+    try {
+      BitbucketPersonalAccessToken bitbucketPersonalAccessToken =
+          bitbucketServerApiClient.getPersonalAccessToken(
+              personalAccessToken.getScmUserName(),
+              Long.valueOf(personalAccessToken.getScmTokenId()));
+      return Optional.of(
+          Sets.difference(DEFAULT_TOKEN_SCOPE, bitbucketPersonalAccessToken.getPermissions())
```
Comment (sparkoo) [inline wsmaster/che-core-api-factory-bitbucket-server/src/main/java/org/eclipse/che/api/factory/server/bitbucket/BitbucketServerPersonalAccessTokenFetcher.java]: `DEFAULT_TOKEN_SCOPE.equals(bitbucketPersonalAccessToken.getPermissions())` will do the same job, is more explicit and without need to use 3rd party library

File: wsmaster/che-core-api-factory-bitbucket-server/src/main/java/org/eclipse/che/api/factory/server/bitbucket/server/AuthorizationSupplier.java [hunk 4]
```diff
@@ -14,8 +14,11 @@
 import org.eclipse.che.api.factory.server.scm.exception.ScmCommunicationException;
 import org.eclipse.che.api.factory.server.scm.exception.ScmUnauthorizedException;
 
-/** Compute the Authorization header to sign the OAuth 1 request. */
-public interface AuthorizationHeaderSupplier {
+public interface AuthorizationSupplier {
```
Comment (sparkoo) [inline wsmaster/che-core-api-factory-bitbucket-server/src/main/java/org/eclipse/che/api/factory/server/bitbucket/server/AuthorizationSupplier.java]: Can you please write javadoc to the interface? Is it bitbucket specific? Shouldn't it have Bitbucket in name then? Is it only oauth1 ?

File: wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/scm/PersonalAccessTokenFetcher.java [hunk 5]
```diff
@@ -30,4 +31,19 @@
...
+   *     that token is valid or @{@link Boolean} value if it can.
+   * @throws ScmUnauthorizedException - in case if user are not authorized che server to create new
```
Comment (sparkoo) [inline wsmaster/che-core-api-factory/src/main/java/org/eclipse/che/api/factory/server/scm/PersonalAccessTokenFetcher.java]:
```suggestion
   * @throws ScmUnauthorizedException - in case if user did not authorized che server to create new
```

File: wsmaster/che-core-api-factory-bitbucket-server/src/main/java/org/eclipse/che/api/factory/server/bitbucket/server/AuthorizationSupplier.java [hunk 6]
```diff
@@ -14,8 +14,11 @@
...
+  /** Compute the Authorization header to sign the OAuth 1 request. */
   String computeAuthorizationHeader(final String requestMethod, final String requestUrl)
       throws ScmUnauthorizedException, ScmCommunicationException;
+
+  /** Construct ScmUnauthorizedException linked to authorization method. */
+  ScmUnauthorizedException buildScmUnauthorizedException();
```
Comment (sparkoo) [inline wsmaster/che-core-api-factory-bitbucket-server/src/main/java/org/eclipse/che/api/factory/server/bitbucket/server/AuthorizationSupplier.java]: this method does not feel right to be in the interface. looks more like helper method.

File: wsmaster/che-core-api-factory-bitbucket-server/src/main/java/org/eclipse/che/api/factory/server/bitbucket/server/AuthorizationSupplier.java (hunk 4 above)
Comment (sparkoo) [inline wsmaster/che-core-api-factory-bitbucket-server/src/main/java/org/eclipse/che/api/factory/server/bitbucket/server/AuthorizationSupplier.java]: Looks like only responsibility of this interface is to calculate the headers. TBH it's not clear to me what does it mean to "compute" the headers. Looking at `AuthorizationSupplier` and `OAuthAuthenticator` I'm a bit confused what are exact responsibilities of these classes and their relations. Probably not the scope of this issue though.

**Comment by skabashnyuk** [comment]
@sparkoo since the responsibility of `AuthorizationSupplier ` was no clearly visible I've moved his functionality to `BitbucketServerPersonalAccessTokenFetcher` as private methods.

File: infrastructures/infrastructure-factory/src/main/java/org/eclipse/che/api/factory/server/scm/kubernetes/KubernetesPersonalAccessTokenManager.java [hunk 7]
```diff
@@ -144,19 +145,24 @@ public PersonalAccessToken fetchAndSave(Subject cheUser, String scmServerUrl)
...
                     annotations.get(ANNOTATION_SCM_USERID),
-                    annotations.get(ANNOTATION_SCM_PERSONAL_ACCESS_TOKEN_ID),
                     annotations.get(ANNOTATION_SCM_PERSONAL_ACCESS_TOKEN_NAME),
-                    new String(Base64.getDecoder().decode(secret.getData().get("token")))));
+                    annotations.get(ANNOTATION_SCM_PERSONAL_ACCESS_TOKEN_ID),
+                    new String(Base64.getDecoder().decode(secret.getData().get("token"))));
+            if (scmPersonalAccessTokenFetcher.isValid(token)) {
+              return Optional.of(token);
+            } else {
+              clientFactory.create().secrets().inNamespace(namespaceMeta.getName()).delete(secret);
```
Comment (metlos) [inline infrastructures/infrastructure-factory/src/main/java/org/eclipse/che/api/factory/server/scm/kubernetes/KubernetesPersonalAccessTokenManager.java:164]: It is not completely obvious to me why we should be deleting the invalid tokens here. Maybe a small comment for the reason behind this? Why don't we for example try `fetchAndSave` in this scenario instead?

Comment (skabashnyuk) [reply infrastructures/infrastructure-factory/src/main/java/org/eclipse/che/api/factory/server/scm/kubernetes/KubernetesPersonalAccessTokenManager.java:164]: Explained in comment https://github.com/eclipse/che/pull/19518/commits/3c99d06df9531d65f9992c1ee01285a216432d0d

**Review by mshaposhnik — APPROVED** [review]

**Review by sparkoo — APPROVED** [review]

**Review by metlos — APPROVED** [review]

**Comment by skabashnyuk** [comment]
crw-ci-test --rebuild
