### PR TITLE
CHE-8675: fix reconnection to a WebSocket entrypoint

### LINKED ISSUE #8675: Dashboard doesn't reconnect to a WebSocket endpoint if the previous connection failed
### Description
Dashboard doesn't reconnect to a WebSocket endpoint if the previous connection failed. As result Dashboard doesn't receive any event about workspaces status changes.

### Reproduction Steps
It happens on all infrastructures Docker, OpenShift, Kubernetes. But it can be reproduced stably only on Kubernetes infrastructure, on other, it happens quite rarely.

I suppose it happens because of `nginx` ingress controller. K8s infra adds new ingress for each workspace server and `nginx` controller restarts itself when new ingress rule is added. So, there is an ability to configure ingress controller for created workspaces ingresses. So only Dashboard should be fixed, and WebSocket connections can be made stable with another ingress controller (I suppose traefik ingress controller can be used for such purposes)

It can be reproduced in the following way:
1. Deploy Che on Kubernetes.
2. Create workspace.
3. Open Developer Console and watch WebSocket connections.
4. Run workspace in IDE.
5. Check a WebSocket connection to wsmaster from the dashboard.
Actual: Dashboard websocket connection is closed, as result Dashboard shows that workspace is STARTING when it is STARTED.
Expected: Dashboard websocket connection is pending, Dashboard receives events that workspace is started and updates Workspace Status Icon.

<details>
<summary>More see screencast</summary>

dashboard_websocket

</details>

**OS and version:**    

**Diagnostics:**

### PR DESCRIPTION
**Pull request by akurinnoy**
Signed-off-by: Oleksii Kurinnyi <okurinny@redhat.com>

### What does this PR do?
This PR adds the ability to handle the 'close' event of JSON-RPC client and tries to re-connect the client if the previous connection fails.

### What issues does this PR fix or reference?
fix https://github.com/eclipse/che/issues/8675

#### Release Notes

N/A - bugfix

#### Docs PR

N/A - bugfix

### CODE REVIEW

**Review by olexii4 — APPROVED** [review]

File: dashboard/src/components/api/json-rpc/che-json-rpc-master-api.ts [hunk 1]
```diff
@@ -36,21 +36,73 @@ const UNSUBSCRIBE: string = 'unsubscribe';
...
+
+    client.addListener('open', () => this.onConnectionOpen());
+    client.addListener('close', () => this.onConnectionClose(entrypoint));
+
     this.cheJsonRpcApi = new CheJsonRpcApiClient(client);
     this.connect(entrypoint);
   }
 
+  onConnectionOpen(): void {
+    this.$log.log('WebSocket connection is opened.');
```
Comment (benoitf) [inline dashboard/src/components/api/json-rpc/che-json-rpc-master-api.ts]: should we keep this log ?

**Review by benoitf — APPROVED** [review]

File: dashboard/src/components/api/json-rpc/che-json-rpc-master-api.ts (hunk 1 above)
Comment (akurinnoy) [reply dashboard/src/components/api/json-rpc/che-json-rpc-master-api.ts]: We could keep this log in case if it is re-connection
```
if (this.reconnectionAttemptNumber !== 0) {
  this.$log.log('...');
}
```
wdyt?

Comment (benoitf) [reply dashboard/src/components/api/json-rpc/che-json-rpc-master-api.ts]: yep

**Review by ashumilova — APPROVED** [review]
