### PR TITLE
CODENVY-1392: fix SSH agent start check

### LINKED ISSUE #1392: Workspace start occasionally fails if docker image doesn't contain ssh and rsync
Workspace start occasionally fails if docker image doesn't contain ssh and rsync. 

Related to:
#1271 
#1371 

**Reproduction Steps:**

Use bitnami stacks to create and start WS several times.

**Expected behavior:**

These WSs start successfully. 

**Observed behavior:**

Sometimes WS start fails and sometimes succeeds. 

**Codenvy version:** m9-snapshot
**OS and version:** Ubuntu 16.04

**Additional information:**

Problem only started happening recently, didn't happen in an older version of Codenvy: [Yes] (because of other reasons such WSs always failed start before merging solution for #1271)
Problem can be reliably reproduced: [No - it's random]

### PR DESCRIPTION
**Pull request by garagatyi**
### What does this PR do?
Chenge check of launch of SSH agent.
Add agent launching checker that checks if command exists
in machine.
Add agent launching checker that checks if port is listened
in machine.
Add agent launching checker that forward check to
several specified checkers.

### What issues does this PR fix or reference?
Fixes codenvy/codenvy#1392

### Previous behavior
Sometimes SSH agent was treated as launched but immediate SSH into container failed.

### New behavior
When SSH agent is treated as launched immediate SSH into container works.

### CODE REVIEW

File: wsmaster/che-core-api-agent/src/main/java/org/eclipse/che/api/agent/server/launcher/AbstractAgentLauncher.java [hunk 1]
```diff
@@ -97,7 +97,6 @@ public void launch(Instance machine, Agent agent) throws ServerException {
         throw new ServerException(errMsg);
     }
 
-
```
Comment (skabashnyuk) [inline wsmaster/che-core-api-agent/src/main/java/org/eclipse/che/api/agent/server/launcher/AbstractAgentLauncher.java:100]: Do you really need this change?

File: wsmaster/che-core-api-agent/src/main/java/org/eclipse/che/api/agent/server/launcher/CommandExistsAgentChecker.java [hunk 2]
```diff
@@ -0,0 +1,54 @@
...
+    @Override
+    public boolean isLaunched(Agent agent, InstanceProcess process, Instance machine) throws MachineException {
+        Command command = new CommandImpl(format("Wait for %s, try %d", agent.getId(), ++counter),
+                                          checkingCommand,
+                                          "test");
+
+        try (ListLineConsumer lineConsumer = new ListLineConsumer()) {
+            InstanceProcess waitProcess = machine.createProcess(command, null);
+            waitProcess.start(lineConsumer);
+            return lineConsumer.getText().endsWith("[STDOUT] 0");
```
Comment (skabashnyuk) [inline wsmaster/che-core-api-agent/src/main/java/org/eclipse/che/api/agent/server/launcher/CommandExistsAgentChecker.java:49]: Do we need to check locale of this command?

**Review by skabashnyuk — APPROVED** [review]

File: wsmaster/che-core-api-agent/src/main/java/org/eclipse/che/api/agent/server/launcher/MappedPortIsListeningAgentChecker.java [hunk 3]
```diff
@@ -0,0 +1,54 @@
...
+        // normalize port/transport value
+        this.exposedPort = exposedPort.contains("/") ? exposedPort : exposedPort + "/tcp";
+    }
+
+    @Override
+    public boolean isLaunched(Agent agent, InstanceProcess process, Instance machine) throws MachineException {
+        Server server = machine.getRuntime().getServers().get(exposedPort);
+        if (server != null) {
+            try {
+                LOG.error("Ping ssh agent");
```
Comment (tolusha) [inline wsmaster/che-core-api-agent/src/main/java/org/eclipse/che/api/agent/server/launcher/MappedPortIsListeningAgentChecker.java]: I think this is debug info.

**Review by tolusha — APPROVED** [review]

File: wsmaster/che-core-api-agent/src/main/java/org/eclipse/che/api/agent/server/launcher/AbstractAgentLauncher.java (hunk 1 above)
Comment (garagatyi) [reply wsmaster/che-core-api-agent/src/main/java/org/eclipse/che/api/agent/server/launcher/AbstractAgentLauncher.java:100]: Why not?

File: wsmaster/che-core-api-agent/src/main/java/org/eclipse/che/api/agent/server/launcher/MappedPortIsListeningAgentChecker.java (hunk 3 above)
Comment (garagatyi) [reply wsmaster/che-core-api-agent/src/main/java/org/eclipse/che/api/agent/server/launcher/MappedPortIsListeningAgentChecker.java]: Yes, nice catch! Thank you.

File: wsmaster/che-core-api-agent/src/main/java/org/eclipse/che/api/agent/server/launcher/CommandExistsAgentChecker.java (hunk 2 above)
Comment (garagatyi) [reply wsmaster/che-core-api-agent/src/main/java/org/eclipse/che/api/agent/server/launcher/CommandExistsAgentChecker.java:49]: It works in the same way as ProcessIsLaunchedChecker. Why do you think locale matters here?
