### PR TITLE
Selenium: add info about known issues, fix unstable selenium tests 

### LINKED ISSUE #9709: It is impossible to create a factory by git URL
### Reproduction Steps
 - Click on the "Factories" button on the dashboard
 - Click on the "Create Factory" button
 - In the opened page click on the "Git" button
 - In the "Git URL" field type link to existing on GitHub project
 - Pay attention that "Create" button is disabled

**Expected behavior:**
Create button is enabled and after clicking on it the factory is created 

**Observed behavior:**
Create button is disabled

**OS and version:**    
Che 6.6.0 ; Chrome 66.0 ; Fedora 25
**Failed selenium test:** CreateFactoryTest

**Attachment:**
eclipse che new factory

**Diagnostics:**

### PR DESCRIPTION
**Pull request by SkorikSergey**
### What does this PR do?
This PR:
- add info about known https://github.com/eclipse/che/issues/11001 issue to **CheckOpenFileFeatureTest** test;
- add info about known https://github.com/eclipse/che/issues/11000 issue to **ProjectStateAfterWorkspaceRestartTest** test;
- add info about known https://github.com/eclipse/che/issues/10854 issue to **WorkingWithTerminalTest** test;
- remove info about resolved #9709 issue from **CreateFactoryTest**;
- increase timeout for checking that project has expected type in **ProjectExplorer** page object.

### What issues does this PR fix or reference?
https://github.com/eclipse/che/issues/11000, https://github.com/eclipse/che/issues/11001

### CODE REVIEW

File: selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/factory/CheckOpenFileFeatureTest.java [hunk 1]
```diff
@@ -90,7 +92,13 @@ public void checkOpenFileFeatureTest() throws Exception {
     loadingBehaviorPage.waitWhileLoadPageIsClosed();
     seleniumWebDriverHelper.switchToIdeFrameAndWaitAvailability();
     projectExplorer.waitItem(PROJECT_NAME);
-    editor.waitTabIsPresent("web-java-spring", ELEMENT_TIMEOUT_SEC);
+
+    try {
+      editor.waitTabIsPresent("web-java-spring", WIDGET_TIMEOUT_SEC);
+    } catch (TimeoutException ex) {
+      // remove try-catch block after issue has been resolved
+      fail("Known issue https://github.com/eclipse/che/issues/11001");
```
Comment (dmytro-ndp) [inline selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/factory/CheckOpenFileFeatureTest.java]: Please, express if it is permanent or random in error message: 
```
Known permanent failure https://github.com/eclipse/che/issues/... 
```

File: selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/miscellaneous/WorkingWithTerminalTest.java [hunk 2]
```diff
@@ -176,34 +176,34 @@ public void shouldResizeTerminal() {
...
+
         terminal.waitTextInFirstTerminal(partOfContent);
-      } catch (TimeoutException ex) {
-        // remove try-catch block after issue has been resolved
-        fail("Known issue https://github.com/eclipse/che/issues/10854");
       }
+      terminal.waitTextInFirstTerminal(".dockerenv");
+    } catch (TimeoutException ex) {
+      // remove try-catch block after issue has been resolved
+      fail("Known issue https://github.com/eclipse/che/issues/10854");
```
Comment (dmytro-ndp) [inline selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/miscellaneous/WorkingWithTerminalTest.java]: Please, express if it is permanent or random in error message: 
```
Known permanent failure https://github.com/eclipse/che/issues/... 
```

File: selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/workspaces/ProjectStateAfterWorkspaceRestartTest.java [hunk 3]
```diff
@@ -95,7 +97,13 @@ private void openFilesInEditor() {
   }
 
   private void checkFilesAreOpened() {
-    projectExplorer.waitItem(PROJECT_NAME + "/src/main/webapp/WEB-INF");
+    try {
+      projectExplorer.waitItem(PROJECT_NAME + "/src/main/webapp/WEB-INF");
+    } catch (TimeoutException ex) {
+      // remove try-catch block after issue has been resolved
+      fail("Known issue https://github.com/eclipse/che/issues/11000");
```
Comment (dmytro-ndp) [inline selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/workspaces/ProjectStateAfterWorkspaceRestartTest.java]: Please, express if it is permanent or random in error message: 
```
Known permanent failure https://github.com/eclipse/che/issues/... 
```

File: selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/miscellaneous/WorkingWithTerminalTest.java [hunk 4]
```diff
@@ -176,34 +176,34 @@ public void shouldResizeTerminal() {
...
-    terminal.waitNoTextInFirstTerminal(".dockerenv");
     consoles.clickOnMaximizePanelIcon();
     loader.waitOnClosed();
 
     // check resize of the terminal
-    for (String partOfContent : CHECK_MC_OPENING) {
-      try {
+    try {
+      for (String partOfContent : CHECK_MC_OPENING) {
+
```
Comment (dmytro-ndp) [inline selenium/che-selenium-test/src/test/java/org/eclipse/che/selenium/miscellaneous/WorkingWithTerminalTest.java]: From readability point it's better to add empty row after `for-statement` than before.

**Review by dmytro-ndp — APPROVED** [review]
